package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(4);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/index/sidecol.jsp");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n<head><title>Perseus Digital Library</title>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/hopper.css\"/>\n<script type=\"text/javascript\" src=\"/js/hopper.js\"></script>\n</head>\n<body onload=\"checkRedirect();\">\n");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n<div id=\"main\">\n    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "includes/index/indexNav.jsp" + (("includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("home", request.getCharacterEncoding()), out, false);
      out.write(" \t\n<div id=\"content\" class=\"2column\">\n        <div id=\"main_col\">\n\t    <div id=\"home\">\n\t    <div align=\"center\"><b>Welcome to Perseus 4.0</b>, also known as the <b>Perseus Hopper</b>. <br>\n\t    <font size=\"-1\">Read more on the <a href=\"/hopper/help/versions.jsp\">Perseus version history.</a>\n\t    <br/>New to Perseus? Click <a href=\"/hopper/help/quickstart.jsp\">here</a> for a short tutorial.\n\t    </font></div>\n\t        <div id=\"news\">\n\t\t    <h4>Announcements</h4>\n\t\t    <ul>\n\t\t     <li>May 23, 2011:\n\t\t     <p>Thanks to a grant from the Google Digital Humanities program, Perseus is pleased to publish TEI XML digital editions of \n\t\t     <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0567\">Dio Chrysostom</a> and \n\t\t     <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0572\">Dionysius</a>.\n\t\t     </p>\n             <p>Support from the Mellon Foundation has allowed us to add TEI XML digital editions for  \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0566\">Jerome</a>,  \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0569\">Minucius Felix</a>, and \n");
      out.write("             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0570\">Tertullian</a>.\n             </p>                            \n\t     <p>This release also includes fixes for line number displays in recently released texts, typos in Elegy &amp; Iambus, the citation scheme in <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0405\">Athenaeus</a> and entity voting errors.</p>\n            </li> \n\t\t    <li>April 14, 2011:\n             <p>Thanks to a grant from the Google Digital Humanities program, \n             Perseus is pleased to publish a TEI XML digital edition of \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0540\">Diodorus</a>. \n             Support for the Cybereditions project from the Mellon Foundation \n             has allowed us to add as well TEI XML digital editions for  \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0536\">Curtius</a>,  \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0537\">Horace</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0543\">Cicero</a>, \n");
      out.write("             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0548\">Ovid</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0549\">Sidonius</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0554\">Prudentius</a> and \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0562\">Seneca the Elder</a>.                             \n             </p>\n             <p>Thanks to support from the U.S. Department of Education and the Max Planck Society\n             we have also been able to publish Edward William Lane's \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2002.02.0015\">Arabic-English Lexicon</a>.</p>                            \n            </li> \n\t\t     <li>March 14, 2011:\n\t\t     <p>Thanks to a grant from the Google Digital Humanities program, \n\t\t     Perseus is pleased to publish a TEI XML digital edition of \n\t\t     <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0530\">Arrian</a>  \n\t\t     and to complete the TEI XML digital edition of <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0511\">Lucian</a>, initially \n");
      out.write("\t\t     published in December. Support for the Cybereditions project from the Mellon Foundation \n\t\t     and Tufts University has allowed us to add as well TEI XML digital editions for  \n\t\t     <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0496\">Florus</a>,  \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0497\">Persius</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0498\"> Statius</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0501\">Apuleius</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0504\">Columella</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0506\">Martial</a>, \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0507\">Tibullus</a> and \n             <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0508:work=1\">the Scriptores Historiae Augustae</a>.               \n             </p>               \n            </li> \n            <li>January 24, 2011:\n            <p>Thanks to a grant from the Google Digital Humanities program, the Perseus Digital Library is pleased to publish TEI XML digital editions for \n");
      out.write("            the Greek Poets <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0483\">Aratus Solensis</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0495\">Colluthus</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0485\">Nonnus of Panopolis</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0481\">Callimachus</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0484\">Lycophron</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0488\">Oppian</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0489\">Oppian of Apamea</a>, \n            <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0490\">Quintus Smyrnaeus</a> \n            and <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0491\">Tryphiodorus</a>.\n            </p>\t\t    \n\t\t    </li> \n\t\t    <li>December 13, 2010:\n\t\t    <ul>Thanks to NEH support for the PhiloGrid Project, the Perseus Digital Library is pleased to publish TEI XML digital editions for \n\t\t    <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0324\">Plutarch</a>, \n");
      out.write("\t\t    <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0405\">Athenaeus</a>, \n\t\t    the <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0472\"><span style=\"font-style:italic;\">Greek Anthology</span></a>, \n\t\t    <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0477\"><span style=\"font-style:italic;\">Elegy and Iambus</span></a> and \n\t\t    for most of <a href=\"/hopper/text?doc=Perseus%3atext%3a2008.01.0471\">Lucian</a>. \n\t\t    This increases the available Plutarch from roughly 100,000 to the surviving 1,150,000 \n\t\t    words. Athenaeus and the <span style=\"font-style:italic;\">Greek Anthology</span> \n\t\t    are new within the Perseus Digital Library, with roughly 270,000 and 160,000 words \n\t\t    of Greek. The 13,000 words for J.M. Edmonds <span style=\"font-style:italic;\">Elegy \n\t\t    and Iambus</span> include both the surviving poetic quotations and major contexts \n\t\t    in which these poems are quoted. The 200,000 words of Lucian represent roughly 70% \n\t\t    of the surviving works attributed to that author. In all, this places more than 1.6 \n");
      out.write("\t\t    million words of Greek in circulation. With this release, we have also changed the \n\t\t    license for opensource texts to <a href=\"http://creativecommons.org/licenses/by-sa/3.0/us/\" \n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/creativeCommons');\">Creative Commons Attribution-ShareAlike</a>,\n\t\t    removing the non-commercial restriction that we adopted in March 2006 when we first \n\t\t    began making our XML source texts available under a CC license. See our post on the\n\t\t    <a href=\"http://www.stoa.org/archives/1332\" onclick=\"javascript: pageTracker._trackPageview('/outgoing/stoa\">Stoa \n\t\t    Consortium</a> blog for full details on the release.\n\t\t    </ul>\n\t\t    </li>\n\t\t    <li>October 22, 2010:\n\t\t    <ul>\n\t\t    <li><b>Updates to Perseus Digital Library:</b> A\n\t\t    new release of the website is now available.  We\n\t\t    have added new texts for current authors, such as\n\t\t    Plutarch and Servius.\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>February 5, 2010:\n\t\t    <ul>\n\t\t    <li>We have fixed the problem with viewing full-size images in IE7 and 8.\n");
      out.write("\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>February 4, 2010:\n\t\t    <ul>\n\t\t    <li>A new release of our source code is now available on <a href=\"http://sourceforge.net/projects/perseus-hopper\" \nonclick=\"javascript: pageTracker._trackPageview('/outgoing/sourceForgeHopper');\">SourceForge</a>. Updated data and text files are also available <a href=\"/hopper/opensource/download\">here</a>.\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>February 1, 2010:\n\t\t    <ul>\n\t\t    <li>Become a fan of Perseus on <a target=\"_blank\" \n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Facebook');\" \n\t\t    href=\"http://www.facebook.com/perseusproject\">Facebook</a>!\n\t\t    </li>\n\t\t    <li><b>Problems viewing images on IE 7 and 8:</b> We are aware of the problem with viewing full-size images through IE 7 or 8 and \n\t\t    are working to fix it. For the best experience on Perseus, we always recommend using the latest version of <a target=\"_blank\" \n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Firefox');\" \n");
      out.write("\t\t    href=\"http://www.mozilla.com/firefox/\">Firefox</a>.</li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>December 15, 2009:\n\t\t    <ul>\n\t\t    <li><b>Updates to Perseus Digital Library:</b> The <a target=\"_blank\" href=\"/hopper/vocablist\">Vocabulary Tool</a> is now \n\t\t    available. For more information about this tool, please see the <a target=\"_blank\" href=\"/hopper/help/vocab\">help page</a>.\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>October 7, 2009:\n\t\t    <ul>\n\t\t    <li><b>Updates to Perseus Digital Library:</b> We have added many new authors and texts \n\t\t    to our collection, including <a href=\"/hopper/searchresults?q=seneca\">Seneca</a>, \n\t\t    <a href=\"/hopper/searchresults?q=quintilian\">Quintilian</a>, \n\t\t    <a href=\"/hopper/searchresults?q=flaccus\">Flaccus</a>, \n\t\t    <a href=\"/hopper/searchresults?q=cicero\">Cicero</a>, \n\t\t    <a href=\"/hopper/searchresults?q=gellius\">Aulus Gellius</a>, \n\t\t    <a href=\"/hopper/searchresults?q=ammianus\">Ammianus</a>\n\t\t     and <a href=\"/hopper/searchresults?q=petronius\">Petronius</a>.\n");
      out.write("\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t     <li>March 31, 2009:\n\t\t    <ul>\n\t\t    <li><b>Updates to Perseus Digital Library:</b> You can now view the places mentioned\n\t\t    in the Perseus Digital Library by <a href=\"/hopper/collections\">collection</a> or text \n\t\t    through the Google Maps interface. Links to view places in a text can be found on a \n\t\t    text page, in the Places box. Places are automatically extracted, so please email the \n\t\t    <a href=\"mailto:webmaster@perseus.tufts.edu\">webmaster</a> if you notice errors.\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t    <li>March 16, 2009:\n\t\t    <ul><li><b>New job announcement:</b> Perseus is seeking a <b><a href=\"/hopper/about/jobs\">Greek Treebank \n\t\t    Editor</a></b> to supervise the creation of a syntactic database for classical Greece with \n\t\t    1,000,000 words - one of the most promising instruments ever produced for the study of Greek \n\t\t    linguistics, literary style, and lexicography.  We encourage graduate students who could build \n\t\t    their dissertation work on this project, as well as classicists with PhD in hand, to consider \n");
      out.write("\t\t    applying.\n\t\t    \n\t\t    </li>\n\t\t    <li><b>Updates to Perseus Digital Library:</b>\n\t\t    <ul>\n\t\t    <li>Many improvements to the Art & Archaeology data and interface.  You can now <a href=\"/hopper/search\">search</a> the \n\t\t    \tA&A data and image captions.\n\t\t    </li>\n\t\t    <li>Euclid's <i>Elements</i> have been added, as well as a large number of Plutarch texts, edited by Bernadotte Perrin.\n\t\t    Links to these texts can be found on the <a href=\"/hopper/collection.jsp?collection=Perseus:collection:Greco-Roman\">Greek and \n\t\t    Roman collection</a> page.\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    </ul>\n\t\t    </li>\n\t\t    \n\t\t   </ul>\n\t\t<p><a href=\"/hopper/help/oldannounce.jsp\">Read older announcements...</a></p> \n\t\t</div>\n\n\t\t<div id=\"contact_info\">\n\t\t    <p>Perseus contact and support <a href=\"/hopper/help\">information</a>.</p>\n\n\t\t    <p>Perseus is a non-profit enterprise, located in the \n\t\t    <a target=\"_blank\"\n\t\t    href=\"http://ase.tufts.edu/classics\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/ClassicsDept');\">Department \n");
      out.write("\t\t    of the Classics</a>, \n\t\t    <a target=\"_blank\" href=\"http://www.tufts.edu\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Tufts');\">Tufts \n\t\t    University</a>.</p>\n\n\t\t\t<p>The Perseus Project is funded by the \n\t\t\t<a target=\"_blank\" href=\"http://alpheios.net\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Alpheios');\">Alpheios \n\t\t\tProject</a>, the \n\t\t\t<a target=\"_blank\" href=\"http://www.mellon.org/\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Mellon');\">Andrew\n\t\t\tW. Mellon Foundation</a>, the \n\t\t\t<a target=\"_blank\" href=\"http://www.ed.gov/\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/DeptOfEd');\">U.S. \n\t\t\tDepartment of Education</a>, the \n\t\t\t<a target=\"_blank\"\n\t\t\thref=\"http://www.imls.gov/\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/IMLS');\">Institute \n\t\t\tof Museum and Library Services</a>, the \n\t\t\t<a target=\"_blank\" href=\"http://www.neh.gov/\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/NEH');\">National \n");
      out.write("\t\t\tEndowment for the Humanities</a>, \n\t\t\t<a href=\"/hopper/help/support.jsp\">private donations</a>, and \n\t\t\t<a target=\"_blank\"\n\t\t\thref=\"http://www.tufts.edu/\"\n\t\t\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Tufts');\">Tufts \n\t\t\tUniversity</a>.\n\t\t\t</p>\n\t    \n\t\t    <p>Support for the project has been provided by the \n\t\t    <a target=\"_blank\" href=\"http://www.learner.org/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Annenberg');\">Annenberg/CPB \n\t\t    Project</a>, \n\t\t    <a target=\"_blank\" href=\"http://www.apple.com/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Apple');\">Apple Computer</a>, the \n\t\t    <a target=\"_blank\"\n\t\t    href=\"http://www.library.tufts.edu/tisch/Berger/bergerhome.html\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Berger');\">Berger \n\t\t    Family Technology Transfer Endowment</a>, \n\t\t    <a target=\"_blank\"\n\t\t    href=\"http://www.dli2.nsf.gov/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/DLI2');\">Digital \n");
      out.write("\t\t    Libraries Initiative Phase 2</a>, \n\t\t    the <a target=\"_blank\"\n\t\t    href=\"http://www.ed.gov/FIPSE/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/FIPSE');\">Fund\n\t\t    for the Improvement of Postsecondary Education</a> \n\t\t    part of the <a target=\"_blank\"\n\t\t    href=\"http://www.ed.gov/\" \n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/DeptOfEd');\">U.S. \n\t\t    Department of Education</a>, \n\t\t    the <a target=\"_blank\"\n\t\t    href=\"http://www.getty.edu/grant/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Getty');\">Getty \n\t\t    Grant program</a>, the \n\t\t    <a target=\"_blank\" \n\t\t    href=\"http://www.mla.org/\" \n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/MLA');\">Modern Language Association</a>, the \n\t\t    <a target=\"_blank\" href=\"http://arts.endow.gov/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/NEA');\">National \n\t\t    Endowment for the Arts</a>, the \n\t\t    <a target=\"_blank\" href=\"http://www.nsf.gov/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/NSF');\">National \n");
      out.write("\t\t    Science Foundation</a>, the \n\t\t    <a target=\"_blank\" href=\"www.packhum.org/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Packard');\">Packard \n\t\t    Humanities Institute</a>, \n\t\t    <a target=\"_blank\" href=\"http://www.xerox.com/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Xerox');\">Xerox Corporation</a>, \n\t\t    <a target=\"_blank\" href=\"http://web.bu.edu/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/BU');\">Boston University</a>, and \n\t\t    <a target=\"_blank\" href=\"http://www.harvard.edu/\"\n\t\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Harvard');\">Harvard University</a>.</p>\n\t\t</div> \n\t    </div> \n\n\t</div> \n\n\t    ");
      out.write("<div id=\"side_col\">\n    <div id=\"texts\" class=\"box\">\n\t<h4>Popular Texts</h4>\n\t<ul>\n\t    <li>Caesar, <span class=\"title\">Gallic War</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.02.0001\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.02.0002\">Latin</a>)</li>\n\t    <li>Catullus, <span class=\"title\">Carmina</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.02.0005\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.02.0003\">Latin</a>)</li>\n\t    <li>Cicero, <span class=\"title\">In Catilinam I</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.02.0019:text=Catil.:speech=1:chapter=1\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.02.0010:text=Catil.\">Latin</a>)</li>\n\t    <li>Vergil, <span class=\"title\">Aeneid</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.02.0054\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.02.0055\">Latin</a>)</li>\n\t    <li>Herodotus, <span class=\"title\">Histories</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.01.0126\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.01.0125\">Greek</a>)</li>\n");
      out.write("\t    <li>Homer, <span class=\"title\">Odyssey</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.01.0136\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.01.0135\">Greek</a>)</li>\n\t    <li>Plato, <span class=\"title\">Republic</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.01.0168\">English</a>, <a href=\"/hopper/text?doc=Perseus:text:1999.01.0167\">Greek</a>)</li>\n\t    <li>Tom Martin, <span class=\"title\">Overview of Classical Greek History from Mycenae to Alexander</span> (<a href=\"/hopper/text?doc=Perseus:text:1999.04.0009\">English</a>)</li>\n\t</ul>\n    </div>\n    <div id=\"artobj\" class=\"box\">\n\t<h4>Art and Archaeology</h4>\n\t<table style=\"text-align: center; margin-left: auto; margin-right: auto;\">\n\t<tr>\n\t<td>\n\t<a href=\"/hopper/artifact?name=Aegina,+Temple+of+Aphaia&object=Building\">\n\t    <img class=\"thumb_img\" src=\"http://images.perseus.tufts.edu/images/thumbs/1987.09.5/1987.09.2169\">\n\t</a>\n\t<div class=\"caption\">\n\tAegina, Temple of Aphaia\n\t</div>\n\t</td>\n\t\n\t<td>\n\t<a href=\"/hopper/artifact?name=BCMA+1914.6.6&object=Coin\">\n");
      out.write("\t\t<img class=\"thumb_img\" src=\"http://images.perseus.tufts.edu/images/thumbs/1989.00.1/1989.00.0214\">\n\t</a>\n\t<div class=\"caption\">\n\tSilver obol from Athens\n\t</div>\n\t</td>\n\t</tr>\n\t\n\t<tr>\n\t<td>\n\t<a href=\"/hopper/artifact?name=Baltimore,+Hopkins+AIA+B3&object=Vase\">\n\t    <img class=\"thumb_img\" src=\"http://images.perseus.tufts.edu/images/thumbs/1990.06.1/1990.06.0255\">\n\t</a>\n\t<div class=\"caption\">\n\tSatyr on Attic red figure vase\n\t</div>\n\t</td>\n\t<td>\n\t<a href=\"/hopper/artifact?name=Boston+03.743&object=Sculpture\">\n\t    <img class=\"thumb_img\" src=\"http://images.perseus.tufts.edu/images/thumbs/1992.03.1/1992.03.0464\">\n\t</a>\n\t<div class=\"caption\">\n\tThe Barlett Head\n\t</div>\n\t</td>\n\t</tr>\n\t</table>\n\t\n    </div> <!-- artobj -->\n    <div id=\"exhibits\" class=\"box\">\n    <h4>Exhibits</h4>\n\t\t    <a href=\"http://www.perseus.tufts.edu/Olympics/\"><img src=\"/img/olicon.gif\" alt=\"The Ancient Olympics\" /></a>\n\t\t    <a href=\"http://www.perseus.tufts.edu/Herakles/\"><img src=\"/img/herc.gif\" alt=\"Hercules: Greece's Greatest Hero\" /></a>\n");
      out.write("\t</div>\n\t\n    <div id=\"featured_sites\" class=\"box\">\n\t<h4>Featured Sites</h4>\n\t<ul>\n\t    <li><a target=\"_blank\" href=\"http://www.stoa.org/\"\n\t    onclick=\"javascript: pageTracker._trackPageview('/outgoing/Stoa');\">Stoa</a>: Open Access Publication\n\t    <ul>\n\t\t<li><a target=\"_blank\"\n\thref=\"http://www.stoa.org/projects/demos/home\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/StoaDemos');\">Demos</a></li>\n\t    </ul>\n\t    <li><a target=\"_blank\"\n\thref=\"http://archimedes.fas.harvard.edu/\" onclick=\"javascript:\n\tpageTracker._trackPageview('/outgoing/Archimedes');\">Archimedes</a>\n\t    <li><a target=\"_blank\" href=\"http://www.tei-c.org\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/TEI');\">The Text Encoding Initiative</a></li>\n\t    <li><a target=\"_blank\" href=\"http://dl.tufts.edu/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/TuftsDL');\">Tufts Digital Library</a></li>\n\t    <li><a target=\"_blank\"\n\thref=\"http://chs.harvard.edu/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/CHS');\">Center for Hellenic Studies</a></li>\n");
      out.write("\t    <li><a target=\"_blank\" href=\"http://arachne.uni-koeln.de/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Arachne');\">Arachne (DAI object database)</a></li>\n\t    <li><a target=\"_blank\" href=\"http://www.dainst.org/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/DAI');\">Deutsches Arch&auml;ologisches Institut</a></li>\n\t    <li><a target=\"_blank\"\n\thref=\"http://www.uni-mannheim.de/mateo/camenahtdocs/camena_e.html\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Camena');\">Camena-Latin\n\tTexts of Early Modern Europe</a></li>\n\t    <li><a target=\"_blank\" href=\"http://www.nyu.edu/isaw/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/ISAW');\">Institute for\n\tthe Study of the Ancient World</a></li>\n\t    <li><a target=\"_blank\"\n\thref=\"http://www.insaph.kcl.ac.uk/index.html\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Aphrodisias');\">Inscriptions of Aphrodisias</a></li>\n\t    <li><a target=\"_blank\"\n\thref=\"http://www.internetcentre.imperial.ac.uk/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/ICL');\">Imperial College London Internet Centre</a></li>\n");
      out.write("\t    <li><a target=\"_blank\"\n\thref=\"http://itreebank.marginalia.it/\" \n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/Thomisticus');\">Index Thomisticus</a></li>\n\t\t<li><a target=\"_blank\"\n\thref=\"http://perseus.uchicago.edu/\"\n\tonclick=\"javascript: pageTracker._trackPageview('/outgoing/PhiloLogic');\">Perseus under PhiloLogic</a></li>\n\t</ul>\n    </div> <!-- featured_sites -->\n</div> <!-- side_col -->\n");
      out.write("\n    </div> ");
      out.write("\n</div> ");
      out.write("\n\n<!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n</body>\n</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
