package org.apache.jsp.help;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class faq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n  <head>\n    <title>Perseus - Help - FAQ</title>\n    <link href=\"/css/hopper.css\" type=\"text/css\" rel=\"stylesheet\"/>\n    <script type=\"text/javascript\" src=\"/js/hopper.js\"></script>\n  </head>\n  <body onload=\"checkRedirect();\">\n    ");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n <div id=\"main\">\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("help", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("faq", request.getCharacterEncoding()), out, false);
      out.write("\n      \n  <div id=\"content\" class=\"2column\">\n   <div id=\"index_main_col\">\n <h3>The Perseus WWW Frequently Asked Questions List</h3>\n <p>\nThis list is a summary of the most frequently asked questions received\nby the Perseus <a href=\"mailto:webmaster@perseus.tufts.edu\">webmaster</a>.  If the\nanswer to your question is not here, please <a href=\"mailto:webmaster@perseus.tufts.edu\">e-mail us</a>.\n<ol>\n<p><b>About Perseus</b><br>\n<li><a href=\"#whatis\">What is the Perseus Digital Library Project?</a>\n<li><a href=\"#free\">Is this site free?</a>\n<p><b>General Questions</b>\n<li><a href=\"#start\">Where do I start?</a>\n<li><a href=\"#info\">How do I find something in Perseus? What types of\nsearches can I do?</a>\n<!-- <li><a href=\"#word\">How do I find the meaning of this Greek or Latin\nword?  My searches aren't returning any results.</a> -->\n<li><a href=\"#trans\">What is the (Greek/Latin/English) translation of\nthis phrase?</a>\n<li><a href=\"#paper\">Will you help me with my project or paper?</a>\n<!-- <li><a href=\"#mail\">Why do I receive an automatic reply to a webmaster\n");
      out.write("question?</a> -->\n\n<p><b>Images</b>\n<li><a href=\"#permiss\">Why does it say that I do not have permission\nto view the image I want to see and how do I get permission?</a>\n<li><a href=\"#copy\">I would like a copy of one of the images I've seen\nin Perseus.  How do I get one?</a>\n<p><b>Texts</b>\n<li><a href=\"#text\">Why don't you have a particular text?</a>\n<li><a href=\"#scroll\">How can I download a complete text file?</a>\n<!-- <li><a href=\"#font\">I'm having trouble viewing the Greek with the\nGreek fonts.  What should I do?</a> -->\n<!-- <li><a href=\"#unicode\">Why do I see wacky question marks or boxes in\nthe middle of Latin words?</a> -->\n<li><a href=\"#typo\">Where do I report a typo? What if I disagree with\nyour translation?</a>\n<!-- <li><a href=\"#hopper\">What are the advantages of the Perseus text\nsystem?</a> -->\n</ol>\n\n<hr><ol>\n<li><a name=\"whatis\"><b>What is the Perseus Project?</b></a>\n<p>The Perseus Project is an evolving digital library of resources for\nthe study of the humanities. We are funded to perform research on\n");
      out.write("developing tools to provide users with improved access to various\ntypes of materials. Past work has focused on building and linking\ntogether collections. Current work considers ways of developing and\nrefining tools for presentation of the materials in the Perseus DL. We\nare primarily a research project, although we do incorporate services\nfor our audience. For more on who we are and what we do, see the <a\nhref=\"/hopper/about\">About Perseus page</a> and our\nlist of <a\nhref=\"/hopper/about/publications\">publications</a>.</p>\n<hr>\n<li><a name=\"free\"><b>Is this site free?</b></a>\n<p>Currently, we offer access to materials free of charge, with the\nexception of certain copyrighted images, <a href=\"#permiss\">noted\nbelow</a>. As we explain elsewhere, we are not funded to provide\nservices, but to do research on how people use these materials and how\nuse may be improved or refined. We offer no warranty on use, as\noutlined <a href=\"http://www.perseus.tufts.edu/site.html\">here</a>. Although portions of the data\nmay be derived from public domain materials, the Perseus Project has\n");
      out.write("created tools and structure to link this data to the remainder of the\nlibrary. Please see <a href=\"/hopper/help/copyright\">copyright\ninformation</a> for more on rights and right holders, and consider <a\nhref=\"/hopper/help/support.jsp\">supporting Perseus</a> with a donation. </p>\n\n<hr>\n<li><a name=\"start\"><b>Where do I start?</b></a>\n<p>There are many ways of accessing the materials in the Perseus\ndigital library. In fact, there is more than one way of getting to the\ncore content of the digital library. <br>\n<div align=\"center\"><img src=\"/img/navigate.gif\"><br><font\nsize=\"-1\">Multiple ways of getting to core Perseus contents.<br>(Or,\nthere's more than one way to slay a Gorgon!)</font></div>Clearly,\nthere are many ways you can begin exploring Perseus content. Which one\nbest suits your particular needs? The answer to that question\ntypically depends on the type of information you require. Read on for\nmore information.<br>\n\n\n\n<hr>\n<li><b><a name=\"info\">How do I find something in Perseus? What types\nof searches can I do?</a></b>\n");
      out.write("<p> The Perseus digital library contains a\nwealth of information but new users can have trouble accessing it all.\nWe at the project are committed to providing resources and tools to\nuse these resources to as many people as possible.  We are not,\nhowever, a research service and we cannot answer specific questions or\nperform customized searches for information.  We encourage users to\ncontinue to make use of local libraries and librarians when doing\nresearch projects.<p> Here are some general suggestions to help\nintroduce you to the way that the Perseus library is set up:<p> <a\nname=\"lookup\"><b>Start </b></a><b>with the <a\nhref=\"/hopper/search\">Perseus lookup\ntool</a>.</b> The lookup tool is a map to the contents of Perseus: its\nresults point you to the subject areas in which you will find\ninformation about your search topic. It is a guide to information\nwithin Perseus; you the user must decide which type of information\nsuits your interest, but be aware that for certain types of inquiries,\nyou may need another tool. The input box for the lookup tool is\n");
      out.write("beneath the &quot;Search&quot; icon on the home page next to the\nbanner image and on every other page in the same general location. You\nneed only type your query in the input box and click the\n&quot;Search,&quot; or the &quot;return&quot; or &quot;enter&quot;\nkey. </a>\n\n<!--<hr>\n<li><b><a name=\"word\">How do I find the meaning of this Greek or Latin\nword?  My searches aren't returning any results.</a></b><p>If you are\na Greek or Latin novice and trying to translate a word or phrase,\ncheck our <a href=\"trans.html\">Greek and Latin translation tips.</a>\n<p>First, check that you're using the correct tool; neither the lookup\ntool nor the English index will find Greek or Latin words. Second, you\nshould check that your Greek or Latin word is properly spelled and\ntransliterated. While the <a href=\"#lookup\">Perseus Lookup Tool</a>\nmentioned above helps you find alternative spellings for various\nEnglish terms, you must be <b>precise</b> when searching for Greek or\nLatin words.  For example, if you are searching for a Greek term in\n");
      out.write("the original Greek, be certain that you are transliterating the\nletters according to the Perseus transliteration system: <br>\n</p>\n<CENTER><IMG SRC=\"/img/latin.gif\"></CENTER><br>(The term \"<a\nhref=\"/cgi-bin/resolveform?lookup=catharsis&type=begin&author=*2.0&options=Sort+Results+Alphabetically&.submit=Submit+Query&formentry=1&lang=Greek\">catharsis</a>\"\nactually begins with a kappa in Greek, so while a search for\n\"catharsis\" in the Greek lexicon will show no results, a search for\n\"<ahref=\"/cgi-bin/resolveform?lookup=katharsis&type=begin&author=*2.0&options=Sort+Results+Alphabetically&.submit=Submit+Query&formentry=1&lang=Greek\">katharsis</a>\"\nwill.)  Each page that calls for transliteration has a chart with the\ncorrect character matches.<p>\nA majority of Greek or Latin searching errors occur when a form other\nthan the basic, uninflected form has been entered.   You must be\ncertain that the word for which you are searching is the <b>correct\nroot form</b>, or else your results will be non-existent or\nincomplete.  Just as you can't check an English dictionary for \"swam,\"\n");
      out.write("and you must look up the basic form of the word, \"swim,\" you can't\ncheck the Greek and Latin lexica for inflected forms of Greek and\nLatin words.  For example, \"ave\" (as in \"Ave, Maria\") is a Latin word,\nbut <a\nhref=\"/cgi-bin/resolveform?lookup=ave&type=exact&author=*Roman&options=Sort+Results+Alphabetically&.submit=Submit+Query&formentry=1&lang=Latin\">a\nsearch for \"ave\" will fail</a>.  You must search for the root form of\n\"ave\" which is \"<a\nhref=\"/cgi-bin/lexindex?lookup=aveo%232&lang=Latin&corpus=Roman&display=\">\naveo</a>.\"  If you are uncertain about the form of the word for which\nyou are searching, you may want to first use the morphological\nanalysis tool for <a\nhref=\"/cgi-bin/morphindex?lang=Greek&corpus=2.0&display=Latin+transliteration\">Greek</a>\nor <a href=\"/cgi-bin/morphindex?lang=Latin\">Latin</a>.  This will tell\nyou the correct root of the word, or at least help narrow your\nsearch.  <a\nhref=\"/cgi-bin/morphindex?lookup=ave&.submit=Analyze+Form&lang=Latin&corpus=Roman&author=&formentry=1\">An\nexample of an analysis of the above Latin word \"ave\" is here.</a>\n");
      out.write("Note that the morphological analysis <b>does not \"disambiguate\"\nforms:</b>  the Latin word \"ave\" could be derived from one of three\nroot words.  The reader must choose which of the three best fits the\ncontext of the word.\n<p>Searches of the Greek and Latin lexica are <b>single word searches\nonly</b>, as are Greek and Latin word searches.  Remember, that common\nGreek terms have often been \"Latinized\" when they enter English, so\ndouble check them before attempting a search in Greek.\n<p><img src=\"/img/comptoolchart.gif\" alt=\"\" height=\"238\"\nwidth=\"776\" border=\"0\"></p> -->\n\n\n<hr>\n<li><b><a name=\"trans\">What is the (Greek/Latin/English) translation\nof this phrase?</a></b>\n<p>If you are a Greek or Latin novice and trying to translate a word\nor phrase, check our <a href=\"/hopper/help/archived/trans.html\">Greek and Latin translation\ntips</a> [note: these tips were written for Perseus 3.0; a 4.0 update is coming soon!]\n<p>\nUnfortunately, the Perseus Project does not have the staff or\nresources to perform custom translation services. Many common phrases may be found via a quick Google search. If you are\n");
      out.write("learning Greek and/or Latin, you may wish to visit the forum page at\n<a href=\"http://www.textkit.com\">Textkit - Greek and Latin Learning\nTools</a>.<br>\n\n\nHere are some of the most commonly asked about phrases (please don't\ne-mail us about these!):\n</p>\n<UL><li><b>illegitimus non carborundum</b> (comes in many variations):\nthis is pseudo-Latin;  check the <a\nhref=\"http://www.google.com/search?hl=en&q=site%3Aomega.cohums.ohio-state.edu+classics-L+carborundum&btnG=Google+Search\">\nclassics list archives</a> for more information.\n<li><b>Lorem ipsum dolor sit amet</b>, . . .. :  it looks like Latin,\nbut it's nonsense. This is the filler text used to demonstrate\nprinting layouts which came into use not long after the printing press\nitself; it persists in  software manuals to this day. It's believed to\nbe a bastardization of some Cicero.  Check the <a\nhref=\"http://www.google.com/search?hl=en&lr=&as_qdr=all&q=+site%3Aomega.cohums.ohio-state.edu+classics-L+lorem+ipsum&btnG=Search\">classics\nlist archives for more information.</a>\n");
      out.write("<li><b>uva uvum (or uvam) vivendo varia fit</b> from <I>Lonesome\nDove.</I> Again, an instance of imperfect Latin. <a\nhref=\"http://www.library.txstate.edu/swwc/ld/ldex081a1.html\">Check\nthis wonderful WWW page</a> for insight into the translation debate.\n</ul>\n<hr>\n<li><b><a name=\"paper\">Will you help me with my project or\npaper?</a></b><p>\nThe Perseus Project is not a research service and we do not have the\nstaff or resources to fulfill all of the requests we receive for\nassistance.  We will gladly assist our users in searching the Perseus\ndigital library, but we cannot answer specific research questions or\ndirect you to relevant sites or bibliography. <p>Some good starting\npoints are <a\nhref=\"http://en.wikipedia.org/wiki/Main_Page\">Wikipedia</a>, <a\nhref=\"http://about.com/\">About.com</a>,  <a\nhref=\"http://www.google.com/\">Google</a>, and <a\nhref=\"http://www.yahoo.com\">Yahoo!</a>.\n\n<!-- <hr>\n<li><b><a name=\"mail\">Why do I receive an automatic reply to a\nwebmaster question?</a></b><p>\nWe receive an average of 20 mails to the webmaster each day; over 100\n");
      out.write("per week. This number is always increasing.  A majority of these\nqueries are answered here in the FAQ or elsewhere (<a\nhref=\"/help/\">other help pages</a>, the <a\nhref=\"/copyright.html\">copyright page</a>, <a\nhref=\"/PerseusInfo.html\">About Perseus</a>, etc.). In order to\ndedicate our limited resources to the questions pertaining to use of\nthe Perseus Digital Library, we have reluctantly instituted the\nautomatic reply. Be aware that <b>if you write from one e-mail address\nand request an answer at another, you may not receive a reply. </b>\n(The automatic reply contains suggestions for other WWW sites of\ninterest and links to pertinent parts of Perseus.) <p>\nWe also want to stress that all mail received at Perseus is not only\nread, but also logged into a webmaster database of incoming mail.  We\nsincerely appreciate your comments, praise, and suggestions for\nimprovement; unfortunately, we won't always be able to tell you so in\na personal reply. All reports of errors are investigated promptly.<p>\n<b>Some tips on receiving a prompt, personal reply:</b> 1) Send your\n");
      out.write("mail in complete sentences, not single words or phrases. We can't\nguess what your question is, so give as much information as\npossible. Also, if you are reporting a problem, include a copy of the\nrelevant  URL(s). 2) Try not to use words like \"urgent\" or include\ndeadlines: our mail, when answered, is answered within five business\ndays and in the order it is received.  We don't prioritize answers,\nrespond on the weekends, or guarantee a reply. To that end.... 3) Do\nnot send homework questions.  We will help you use Perseus to find an\nanswer: we do not send out the answer.  If you ask an obvious homework\nquestion, you will <b>not</b> receive a reply.  If you ask for help\nusing Perseus, you will. 4) Make your criticism constructive.  General\ncomments are good, but if you have a problem with Perseus <b>be\nspecific</b>. If you want to know why we do (or don't do) something,\nwe'll tell you. Just ask!  Be considerate of the webmaster and write\nonly mail you would like to receive. 5) Do not use all uppercase\nletters: in most circles, this is considered bad \"Netiquette\" and\n");
      out.write("conveys a sense of urgency (see item 2 above) or shouting. No one\nlikes to be shouted at! <p><b>Remember the more information you give\nus, the better equipped we are to answer you quickly, accurately and\ncompletely!</b> -->\n\n<hr>\n<li><b><a name=\"permiss\">Why</a>\n<a name=\"sculpt\">does it say that I do not have permission\nto view the image I want to see and how do I get permission?</a></b>\n<p>\nMany of the <a href=\"http://www.perseus.tufts.edu/hopper/collections\">art\nand archaeology</a> objects in the Perseus digital library are owned\nby museums.  Perseus <a\nhref=\"/hopper/help/copyright\">does not have\npermission</a> to display all of the images of these objects on the\nWWW. Currently, we provide images from the following:<ul>\n<li>all of the images in the\n<a\nhref=\"/hopper/artifactBrowser?object=Building\">Building</a>\nand <a\nhref=\"/hopper/artifactBrowser?object=Site\">site</a>\ncatalogs; \n<li>the sculpture collections from the<ul>\n<li><a\nhref=\"/hopper/artifactBrowser?object=Sculpture&field=Collection&value=Museum+of+Fine+Arts,+Boston\">Museum\n");
      out.write("of Fine Arts, Boston</a>, <li>the <a\nhref=\"/hopper/artifactBrowser?object=Sculpture&field=Collection&value=Berlin,+Antikenmuseen\">Berlin\nAntikenmuseen</a>, and <li>the <a\nhref=\"/hopper/artifactBrowser?object=Sculpture&field=Collection&value=Paris,+Mus%26%23233%3Be+du+Louvre\">Mus&eacute;e\ndu Louvre, Paris</a>;\n</ul><li>the <a\nhref=\"/hopper/artifactBrowser?object=Coin&field=Collection&value=Arthur+S.+Dewing+Collection\">Dewing coin collection</a>;\n\n<li>and vase collections from the\n<ul>\n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Berlin,+Antikenmuseen\">Berlin\nAntikenmuseen</a>,\n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Paris,+Mus%26%23233%3Be+du+Louvre\">Mus&eacute;e\ndu Louvre, Paris</a>,<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Museum+of+Fine+Arts,+Boston\">Museum\nof Fine Arts, Boston</a>, \n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Cambridge,+Harvard+University+Art+Museums\">Harvard\nUniversity Art Museums</a>,\n");
      out.write("<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=University+Museums,+University+of+Mississippi\n\">University of Mississippi</a>,\n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=University+Museum,+University+of+Pennsylvania\">University\nof Pennsylvania</a>,\n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Museum+of+Art,+Rhode+Island+School+of+Design\">Rhode\nIsland School of Design</a>,\n<li><a\nhref=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Tampa+Museum+of+Art\">Tampa\nMuseum of Art</a> and\n<li><a href=\"/hopper/artifactBrowser?object=Vase&field=Collection&value=Toledo+Museum+of+Art\">Toledo Museum of Art</a>.\n</ul>\n</ul>\n<hr>\n<li><b><a name=\"copy\">I would like a copy of one of the images I've\nseen in Perseus, how do I get one?</a></b><p>\nThe credit notices for all images appear at the top of each image\npage.  If this notice reads \"...courtesy of X museum,\" you must\ncontact the named museum for permission to reproduce their image.\nAddresses for museums are at the bottom of our <a\n");
      out.write("href=\"/hopper/help/copyright\">copyright page</a>. <p>The Perseus Project does\nnot have permission or resources to redistribute images. No image\ncontained in the Perseus digital library may be reproduced in any form\nwithout permission of the copyright holders. We cannot authorize reuse\nof Perseus images on other WWW sites, even for educational, non-profit\nuse. If you have further questions about images, <a\nhref=\"mailto:webmaster@perseus.tufts.edu\">please contact us</a>.\n\n<hr>\n<li><b><a name=\"text\">Why don't you have a particular text?</a></b><p>\nThe Perseus Project's initial focus was the ancient Greek world.\nSubsequent growth of the library into the Roman era and the\nRenaissance, including the works of Christopher Marlowe, has been a\ngradual process. Since we are a grant-funded project, we have limited\nresources at our disposal. If you have suggestions for future work,\nplease let us know. We log all suggestions for future expansion.\n\n<hr>\n<li><b><a name=\"scroll\">How can I download a complete text\nfile?</a></b><p>\n");
      out.write("Our <a href=\"/hopper/help/copyright\">copyright</a> agreements with the\npublishers of our texts do not permit us to offer full text\ndownloading for all works in Perseus at this time. Texts for which xml downloads are available are indicated as such by a creative commons license and links to download options. You will find these in the center of a text viewing page, below the main focus text. We do not offer other formats for texts at this time. \n We realize that users with slower connections or those who prefer reading texts off of a hard copy, not\nthe computer screen, prefer a downloading option.  The addresses for the\npublishers of the texts are provided on our <a\nhref=\"/hopper/help/copyright\">copyright page</a> if our readers wish to\npurchase the books. <a href=\"http://www.textkit.com\">Textkit - Greek and Latin Learning\nTools</a> is a fine site with many public domain texts in downloadable .pdf format.\n<!--<hr>\n<li><b><a name=\"font\">I'm having trouble viewing the Greek with the\nGreek fonts.  What should I do?</a></b>\n");
      out.write("<p>\nFirst, check our <a href=\"/Help/fonthelp.html\">font help page</a> for\nmore information on the many options for viewing Greek. This page\ncontains important instructions, information, and notices of known\nfont &quot;bugs.&quot; Please follow all of the steps outlined on\nthese pages before contacting us with your questions. Also note that\nthese instructions are subject to change, so if you have used fonts in\nthe past but they are not working now, check the updated\ninstructions. If you are having difficulty installing fonts, please\ncheck your user manual or ask your local technical advisor. The\nPerseus Project does not have the staff to answer font installation\nquestions. Perseus provides some fonts for reading texts: you may not\nbe able to use these fonts to type Greek characters. -->\n<!-- <hr><li><a name=\"unicode\"><b>Why do I see wacky question marks or boxes in\nthe middle of Latin words?</b></a>\n<p>This is a problem with Unicode display on some browsers and\nplatforms. Not all browsers are able to correctly map Unicode\n");
      out.write("characters. You'll most likely encounter this problem with macrons\nappearing in Latin words (such as in the Latin grammar or Latin\ndictionaries). If your system should be able to read Unicode (Windows\nrunning IE), make sure you have followed the steps in the <a\nhref=\"/help/fonthelp.html\">font display help section</a>. Also, double\ncheck that your browser is accepting cookies.</p>\n<p>If you are using another system, such as a Mac, we suggest changing\nthe way your display is configured to read Greek. (This sounds\ncounter-intuitive for reading Latin!) Recent testing on a Mac\neliminated the question marks by setting the Greek display to\nSuperGreek on both IE and Netscape. (NB: Netscape 4.75 was tested, not\nNetscape 6.) Again, be sure that you are accepting cookies. You need\nnot install SuperGreek for this to work. The macrons will appear as\ncircumflex accents, not macrons, but you may find this less\ntroublesome to view. Tips on configuring your display are linked from\nthe <a href=\"/help/TextHelp.html#display\">text help section</a>.</p> -->\n");
      out.write("\n<hr><li><b><a name=\"typo\">Where do I report a typo? What if I disagree\nwith your translation?</a></b><p>\nAt this time, all reports of typographical errors should be sent to\nthe Perseus <a\nhref=\"mailto:webmaster@perseus.tufts.edu\">webmaster</a>. Please\nprovide the exact text citation. We rely on our users to bring these\nto our attention, and welcome all reports. These will be logged and\ninvestigated. In the case of variant readings, Perseus follows the\noriginal print edition of the on-line text.<p><b>Perseus does not\ntranslate works.</b> You may disagree with the translation of a work provided in Perseus; this is to be expected. Keep in mind, however, that Perseus is a digital library and we are not the authors of the translations in the digital library, no more than your local librarian is the author of every book in his or her library.<p><b>Perseus does not alter the content of a print work</b> when it\nis converted to an electronic version except to regularize spelling\nand remove archaisms. In some rare cases, we have entered older source\n");
      out.write("materials which may contain outdated information which has been\nsuperseded by recent research. Always check the publication date on\nmaterials. We have made an effort to provide as many materials as\npossible, and in doing so, we have had to rely on older, public domain\nsources.</p>\n<!-- <li><a name=\"hopper\"><b>What are the advantages of the Perseus text\nsystem?</b></a>\n<p>We implemented the current version of the text system in response\nto user comments and suggestions. First, users had trouble finding\ntexts and works within Perseus. The new <a\nhref=\"/cgi-bin/perscoll\">Perseus table of contents page</a> shows you\nall of the contents of Perseus at once. You may customize this listing\nfor specific collections and/or languages. This is done automatically\nnow, and not on a static page. This means that the contents are always\nup-to-date. The basis of this system is a new and improved means of\neasily adding texts to the Perseus digital library, following the\nexample of Perseus images. Second, users requested more display\n");
      out.write("options, such as a &quot;cookie&quot; for preserving display options\nand the choice of the default text language. Third, navigation within\na text was not intuitive. We now have a go to navigation box, a\nnavigation bar, and arrows within every text. This helps you find a\nspecific passage more quickly and see your relative location within a\ntext. Fourth, we improved the searching tools, added new texts and\ncommentaries, and added new features such automatic text links to the\nnew <a href=\"/cgi-bin/patlas\">Perseus Atlas</a> and cross reference\nlinks. Beneath it all, we more than doubled our processor power for\nWWW service. This new system means we will be better able to deliver\nfuture additions to the Perseus Digital Library. So, check the <a\nhref=\"/help/tochelp.html\">table of contents help page</a> and the <a\nhref=\"/help/TextHelp.html\">updated text help page</a> and try it\nout!</p> -->\n</ol>\n<hr>\n<i>document created: 1/12/98</i><br>\n<i>document last revised: 8/30/07</i><br>\n<i>LMC</i>\n</div> <!-- main_col -->\n\n     </div> <!-- content 2column -->\n");
      out.write("    </div> <!-- main -->\n    \n    <!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n  </body>\n</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
