package org.apache.jsp.help;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class texts_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n<head><title>Perseus 4.0 Text Help</title>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/hopper.css\"/>\n<script type=\"text/javascript\" src=\"/js/hopper.js\"></script>\n</head>\n<body onload=\"checkRedirect();\">\n");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n<div id=\"main\">\n\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("help", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("texts", request.getCharacterEncoding()), out, false);
      out.write("\n\t<div id=\"content\" class=\"2column\">\n\t\t<div id=\"index_main_col\">\n\t\t<h3>Perseus 4 Text Help</h3>\n\t\t<p><b><a id=\"quick\" name=\"quick\">Quick overview of the page:</a></b>\n\t\t<br>There are several ways to access a text: consult the <a href=\"quickstart\">Quick Start Guide</a> for more help.  In this example, we'll start with the beginning of Ovid's \n\t\tMetamorphoses in Latin. In most cases, the layout of a text page will be similar to this (there may be slight differences for secondary sources or reference works).</br>\n\t\t\t\t\t\n\t\t<p><img src=\"/img/help/texthelp2.png\" alt=\"image of start of Ptext 1999.02.0029\" border=\"1\"><br>\n\t\t<font size=\"-1\">Figure 1: Diagram of Ovid's Metamorphoses (Latin, Magnus, ed.) 1999.02.0029; center of page</br></font></p>\n\t\t\t\t\t\n\t\t<p>The center of a typical text page will have the essential information you need: focus text, navigation tools, credits information, and download links.</p>\n\n\t\t<p><img src=\"/img/help/texthelp1.png\" alt=\"image of start of Ptext 1999.02.0029\" border=\"1\"><br>\n\t\t<font size=\"-1\">Figure 2: Diagram of Ovid's Metamorphoses (Latin, Magnus, ed.) 1999.02.0029; sidebars of page</br></font></p>\n");
      out.write("\t\t\t\t\t\n\t\t<p>The sidebars of the typical text page will have supplemental information about a text: the left sidebar has information the collections in which this work is found, \n\t\tdifferent ways of chunking the text, and a document-specific table of contents; the right sidebar has additional links to other editions of this work, cross references, \n\t\tvocabulary, searching specific to this document, and display preferences.</p>\n\t\t\t\t\t\n\t\t<p><b><a id=\"persist\" name=\"persist\">Persistent content</a></b> appears at the top of each page above the gray bar with collection links. This content is regular throughout \n\t\tPerseus and includes the document/collection/tool title and general searching box.\n\t\t<br><b><a id=\"title\" name=\"title\">Document Title</a></b> appears at the top of each page. If you are in a general part of the site (research, help, etc.) this may be identical \n\t\tto the home page.  Otherwise, it will change to the specific document or tool you are using.</br>\n\t\t<br><b><a id=\"gensearch\" name=\"gensearch\">Searching (general)</a>:</b> the collection wide search tool appears in the top right corner of each page of Perseus.  The default \n");
      out.write("\t\tsearch is a metadata collection-wide search.  For searching related to the focus text and language, see the <b>document-focused searching</b> below.</br></p>\n\t\t\t\t\t\n\t\t<p><b><a id=\"center\" name=\"center\">Center of the Page</a></b>:\n\t\t<br><a id=\"focus\" name=\"focus\">The <b>Focus Text</b></a> is at the heart of the page. This is the selected document. The amount of text you see depends on the default chunking \n\t\tsettings for the particular work. Some works default to small sections; others, larger ones. In general, the selection tends to be small to enable faster page loading. To \n\t\tchange the size of the chunk you are viewing, see <b>Text Chunking Options</b> below.</br>\n\t\t<br><a id=\"browse\" name=\"browse\">Above the Focus Text and immediately below the gray collection links bar, is the <b>Browse Bar,</b></a> providing a quick overview of the \n\t\tstructure of the text and relative size of the section you are currently viewing. Your current position will be marked in blue; other parts or chunks of the text will be in \n");
      out.write("\t\tgray. Since every text is divided differently (books/chapters, sections, chapter/verse, etc.), the layout of the browse bar will vary. The browse bar permits you to jump to \n\t\tdifferent sections of a work and get a sense of the relative length of a work. (Is line 500 of this play near the beginning, middle, or end?) The browse bar of the lexica and \n\t\tother reference works have a top line divided alphabetically, followed by further alphabetical subsections which allow you to jump to any given entry in three steps. As with \n\t\tmost features on the text pages, you may hide the browse bar by clicking the link on the right side of the bar.</br>\n\t\t<br><a id=\"navarr\" name=\"navarr\">Just above the Focus Text, blue <b>Navigation Arrows</b></a> appear, permitting you to \"page\" through the focus text section by section. You \n\t\tmay see both forward and back arrows or just one of the two, depending on your location in a given text.  When you are at the start of the text, as in the above pictured \n\t\texample, only the forward, right-pointing, arrow appears.</br>\n");
      out.write("\t\t<br><a id=\"jump\" name=\"jump\">To the right of the arrows, is the text <b>\"Jump Box.\"</b></a> Similar in size and appearance to a typical search box, this box permits you to \n\t\tjump to another section of the work or another Perseus work by using the standard Perseus text citation. It is preloaded with your current text section (Ov. Met. 1.1 in our \n\t\texample). It is not a standard search box, however, and is only used for navigating within the texts.</br>\n\t\t<br><b>To use the Jump Box</b>, simply enter the standard Perseus citation abbreviation to jump to a specific author and work. This is most helpful if you are researching \n\t\tseveral sections within a specific text. (Reading Ov. Met. 1.1, 5.3, and 8.2, for instance). <b>What is the standard Perseus citation abbreviation for a given author and \n\t\twork?</b> Check the  [view abbreviations] link just under the top right general search box.  Note you can also use these citation abbreviations in the general search box, \n\t\ttoo.</br>\n\t\t<br>J<a id=\"credits\" name=\"credits\">ust below the focus text, are the <b>Credits</b></a> where you will find bibliographic information about the document, funder information, \n");
      out.write("\t\tand notes on the level of accuracy, if applicable. Underneath the credits, are more navigation arrows (there so that you do not have to scroll up the page when reading a large \n\t\tsection of text) and an orange <a id=\"xml\" name=\"xml\"><b>XML button</b></a> which allows you to see the xml for this chunk of focus text.  You can either view this in your \n\t\tbrowser or save it to use in another program. This button only offers xml for the chunk of text you are viewing and is available for all works in Perseus regardless of \n\t\tcopyright status.</br>\n\t\t<br><a id=\"downld\" name=\"downld\">At the bottom center of the page, <b>Download and License</b></a> information appears, if applicable. In this example, the focus text is in \n\t\tthe public domain, and a full download of the xml source of the text is offered under a Creative Commons license. Certain works are not offered for full download, either \n\t\tbecause we do not believe them to be in the public domain or they are not ready for release. See the <a href=\"copyright\">copyrights page</a> for more on permissions, downloads, \n");
      out.write("\t\tfair use, etc.</br></p>\n\t\t\t\t\t\n\t\t<p><b><a id=\"left\" name=\"left\">Left Side of the Page</a></b>:\n\t\t<br><a id=\"partof\" name=\"partof\"><b>This Text is Part of:</b></a> The uppermost gray box to the left of the text denotes the collection(s) and categories to which the current \n\t\ttext belongs and offers links to view similarly classified documents or works by the same author. There are often multiple versions of a work in Perseus (original language, \n\t\tdifferent translations).</br>\n\t\t<br><a id=\"chunk\" name=\"chunk\"><b>View Text Chunked by:</b></a> In most cases, you will have the option of changing the way the focus text is divided for reading. This box, \n\t\tmidway down the left sidebar, allows you to change the amount of text you see on a page.  Be aware that selecting another option, particularly a larger designation, such as \n\t\ta whole book rather than a chapter or section, may slow performance.</br>\n\t\t<br><a id=\"toc\" name=\"toc\"><b>Table of Contents</b>:</a> for the focus text appears in the lower gray box of the left sidebar. For works with subsections or particularly large \n");
      out.write("\t\tdocuments, click on the blue toggle triangles to view more information. Table of Contents divisions will match those of the Browse bar, but often provide greater detail.</p>\n\n\t\t<p><a id=\"right\" name=\"right\"><b>Right Side of the Page</b>:</a>\n\t\t<br><a id=\"alted\" name=\"alted\"><b>Alternate Editions</b></a> When different Perseus editions or translations of the focus text are available, these will appear at the top of \n\t\tthe right sidebar. The language of the text and the editor(s) are displayed in a gray bar, along with \"focus\" and \"load\" links. Clicking the \"focus\" link will change the \n\t\tcentral display text to the selected focus text. Clicking the \"load\" link will display the focus passage in the indicated alternate edition. Once you have loaded an alternate \n\t\tedition, the \"load\" link changes to \"show\" or \"hide.\" If the alternate edition is already being shown, the \"hide\" link will close it. To show it again, click \"show.\" <i>Note \n\t\tthat Perseus is matching sections of texts based on numeration, not content. If alternate editions come from different sources, translations may not correspond exactly. \n");
      out.write("\t\tEditors may have numbered works differently, moved, or removed text based on variant manuscript traditions.</i></br>\n\t\t<br><a id=\"ents\" name=\"ents\"><b>Entities and Cross references</b></a> By default, the page shows links to automatically extracted named entities (people, places, dates) and \n\t\tcross-references to the focus passage in other Perseus works, most commonly grammars, commentaries, and lexica. These may be hidden with the \"hide\" link. Named entities, \n\t\tidentified by the Perseus Digital Library system, may be sorted in other ways, as indicated. All entities are linked to Perseus searching for the chosen document. As with \n\t\tother right sidebar items, these may be shown or hidden via \"show/hide\" links.</br>\n\t\t<br><a id=\"vocab\" name=\"vocab\"><b>Vocabulary Tool</b>:</a> When reading in a primary language edition, this shows a short vocabulary list for the current passage of the focus \n\t\ttext. This tool analyzes all of the forms in the given passage and sorts entry forms by frequency. Since some words may have more than one dictionary form, all possible forms \n");
      out.write("\t\tfor a given word are included. These ambiguous words will produce multiple results, some of  which may not reflect the meaning of a word in the given passage. The usefulness \n\t\tof the frequencies depends on the size of the passage. Larger passages may produce more useful results. You may link to the full <a href=\"/hopper/vocablist\">Vocabulary Tool</a> \n\t\tvia this sidebar. For more information, see the <a href=\"vocab\">Vocabulary Tool help</a>.</b></br>\n\t\t\t\t\t\n\t\t<br><a id=\"contextsearch\" name=\"contextsearch\"><b>Search (contextual)</b>:</a> A contextualized search box appears for the focus text: this is the same as the general search \n\t\tbox (upper right of the page) preloaded with settings pertaining to the focus text. It will match the language of the focus text by default (if you are reading a Latin text, \n\t\tsearching will be in Latin) and be preset to search only the document you are viewing. To search in another language, or further customize your search, follow the \"More search \n\t\toptions\" link to the general search tools.  If you are searching in an inflected language, you'll have the option of searching on inflected or exact forms. Other options may \n");
      out.write("\t\tappear depending on the work.</br>\n\t\t\t\t\t\t\n\t\t<br><a id=\"display\" name=\"display\"><b>Display Preferences</b>:</a> Here, set a preference for displaying Greek (or Arabic), either with a particular Greek font style or \n\t\ttransliteration and choose a default text view when reading works Perseus features in both original and translation. Choose \"Original Language\" if you prefer to study works \n\t\tin the original Greek, Latin, et al; \"Translation\" gives you the English translation of the work. This is particularly useful if you regularly use Perseus citation \n\t\tabbreviations to access works rather than collections or contents pages.You may also choose to show or hide the Browse bar by default. Clicking the Update Preferences button \n\t\twill save your preferences for future Perseus sessions.</br>\n\t\t<hr>\n\t\t<i>revised  22-Dec-09, LMC</i>\n\t\t</p>\t\t\t\n\t</div><!-- main_col div -->\n\t\t\t\t\n\t<div id=\"img_side_col\" style=\"font-size:small; text-align:left\">\n\t\t<h4>Perseus 4 Text Help</h4>\n\t\t<ul><li><a href=\"#quick\">Quick overview of the page</a></li>\n");
      out.write("\t\t\t<li><a href=\"#persist\">Persistent content</a></li>\n\t\t\t\t<ul><li><a href=\"#title\">Document title</a></li>\n\t\t\t\t<li><a href=\"#gensearch\">Searching (general)</a></li>\n\t\t\t\t</ul>\n\t\t\t<li><a href=\"#center\">Center of the page</a></li>\n\t\t\t\t<ul><li><a href=\"#focus\">Focus Text</a></li>\n\t\t\t\t<li><a href=\"#browse\">Browse Bar</a></li>\n\t\t\t\t<li><a href=\"#navarr\">Navigation Arrows</a></li>\n\t\t\t\t<li><a href=\"#jump\">Jump Box</a></li>\n\t\t\t\t<li><a href=\"#credits\">Credits</a></li>\n\t\t\t\t<li><a href=\"#xml\">XML Button</a></li>\n\t\t\t\t<li><a href=\"#downld\">Download and License</a></li>\n\t\t\t\t</ul>\n\t\t\t<li><a href=\"#left\">Left Side of the Page</a></li>\n\t\t\t\t<ul><li><a href=\"#partof\">This Text is Part of</a></li>\n\t\t\t\t<li><a href=\"#chunk\">View Text Chunked by</a></li>\n\t\t\t\t<li><a href=\"#toc\">Table of Contents</a></li>\n\t\t\t\t</ul>\n\t\t\t<li><a href=\"#right\">Right Side of the Page</a></li>\n\t\t\t\t<ul><li><a href=\"#alted\">Alternate Editions</a></li>\n\t\t\t\t<li><a href=\"#ents\">Entities and Cross references</a></li>\n\t\t\t\t<li><a href=\"#vocab\">Vocabulary Tool</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#contextsearch\">Search (contextual)</a></li>\n\t\t\t\t<li><a href=\"#display\">Display Preferences</a></li>\n\t\t\t\t</ul>\n\t\t\t</ul>\n\t\t</div>\n\t</div><!-- 2column div -->\n</div><!-- main div -->\n\t\t\n<!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n\n</body>\n</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
