package org.apache.jsp.help;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class vocab_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n  <head>\n    <title>Perseus Vocabulary Tool Help</title>\n    <link href=\"/css/hopper.css\" type=\"text/css\" rel=\"stylesheet\"/>\n    <script type=\"text/javascript\" src=\"/js/hopper.js\"></script>\n  </head>\n  <body onload=\"checkRedirect();\">\n\n    ");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n    <div id=\"main\">\n      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("help", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("vocab", request.getCharacterEncoding()), out, false);
      out.write("\n\n      <div id=\"content\" class=\"2column\">\n      <div id=\"index_main_col\">\n      <h3>Perseus Vocabulary Tool Help</h3>\n\t\t\t\t<p>The Perseus Vocabulary Tool is designed to allow users to explore the vocabulary of the non-English texts in the Perseus Digital Library.  Using \n\t\t\t\tthe Vocabulary Tool you can select a set of documents or document sections and then view a list of all of the words that appear in that selection.</p>\n\n<ul>\n<li>Setting Up Your List</li>\n<ul>\n<li><a href=\"#worksel\">Selecting Sections or Works</a></li>\n<li><a href=\"#sortorder\">Sort Order</a></li>\n<li><a href=\"#listlen\">List Length</a></li>\n<li><a href=\"#oopts\">Output Formats</a></li>\n");
      out.write("\n</ul>\n<li>Viewing the Results</li>\n<ul>\n<li><a href=\"#size\">Vocabulary Size and Density</a></li>\n<li><a href=\"#list\">The Vocabulary List</a></li>\n<li><a href=\"#freqs\">Maximum, Minimum, and Weighted Frequencies</a></li>\n<li><a href=\"#tfidf\">Key Term Scores</a></li>\n<li><a href=\"#refine\">Refining Your Word List</a></li>\n</ul>\n<li>Things You Can Do with the Vocabulary Tool</li>\n<ul>\n<li><a href=\"#comp\">A Comprehensive Vocabulary List for a Work</a></li>\n<li><a href=\"#authess\">A List of Essential Words for an Author</a></li>\n<li><a href=\"#inter\">A List of Basic Words for Intermediate-Level Reading</a></li>\n<li><a href=\"#compess\">A List of Essential Words for a Comprehensive Greek or Latin Exam</a></li>\n<li><a href=\"#keylist\">A List of Keywords for a Text</a></li>\n</ul>\n  <li><a href=\"#wft\">Word Frequency Tool</a></li>\n  <ul><li><a href=\"#max\">Why are there Maximum and Minimum Frequencies?</a></li>\n    <li><a href=\"#weight\">What is a Weighted Frequency?</a></li>\n    <li><a href=\"#rel\">Why use relative frequencies?</a></li>\n");
      out.write("  </ul>\n</ul>\n<hr>\n\n\n<h3><a name=\"settingup\"></a>Setting Up Your List</h3>\n\n<p>There are two ways to access the Vocab Tool depending on what you are looking for:</p>\n\n");
      out.write("\n<p><a name=\"worksel\"></a><b>Subsection of a Text</b>: If you want the vocab for a particular section of a text, say <a href=\"/hopper/text?doc=Perseus:text:1999.01.0133:book=1\">Book \n1 of the Iliad</a>, then you would view that section on the text page, and click <em>load</em> in the <b>Vocabulary Tool</b> box. By default, this box will show you \nthe top 50% of words in that section, sorted by <a href=\"#weight\">weighted frequency</a>. The box will provide a link to further refine how the vocab is sorted \nand displayed, as described <a href=\"#sortorder\">below</a>.</p>\n\n<center><img src=\"/img/help/vocab.first.gif\"></center>\n<p><b>Full Text(s)</b>: If you want to view the vocab for a full text or multiple texts, you will need to access the <a target=\"_blank\" href=\"/hopper/vocablist\">Vocabulary Tool</a> page. \nHere, you are presented with a selection box that shows all of the works in a language in a Perseus collection (see above figure).  You can select the documents for your vocabulary list by \nselecting the documents in this box.  As usual, Macintosh users can select more than one work by holding the Command key as they click, and Windows users can select more \n");
      out.write("than one work by holding the Control key.  You may select as many works as you like, though your results may be slow to load if you choose too many texts.\n</p>\n\n<p>\n<b><a name=\"sortorder\"></a>Sort Order</b>:  It is possible to select several ways to sort your list.  Different sort orders are useful for different tasks.\n<ul>\n<li>An <strong>alphabetical listing</strong> will allow you to generate a traditional word list that you can use to help you study a text.  \n<li>A list ordered by either <a href=\"#weight\">weighted</a> or <a href=\"#max\">maximum</a> <strong>frequency</strong> will allow you to generate a list of the most common \nwords in a text.  This will allow you to know what words are important to learn to help you read a text more effectively.  \n<li>A list ordered by the <strong>key word score</strong> will provide an initial guide to the distinctive words in your selection of texts.   Words with a high 'key word' \nscore appear relatively often in your document selection but appear relatively infrequently in other documents in the collection in the Perseus Digital Library.  The five \n");
      out.write("or ten words with the highest key word scores are frequently the names of the important people, places, and concepts in your selection of works.  See \n<a href=\"#tfidf\">below</a> for more information and detailed examples.\n</ul>\n\n\n<p><strong><a name=\"listlen\"></a>List Length</strong>:  The tool also allows you to select the percentage of the words in a document that you want to include in your \nlist.  As with the sort orders, the different percentages are useful for different purposes.  The vast majority of words in any text appear only once.  If you are looking \nfor a list that contains the essential vocabulary for your selected texts, pick a higher percentage.  If you want a comprehensive list, pick a lower percentage or the \n\"all words\" option. Selecting an alphabetical listing of words works best when displaying all words in your selection.  \n\n<p><strong><a name=\"oopts\">Output Formats</a></strong>:  The vocabulary tool provides two different ways to format your output.  You can choose a table that will provide \n");
      out.write("attractive output in a web browser or an XML file that you can import into other software programs.  Note that some browsers have problems displaying very \nlarge tables;  if you are requesting a very long list, the XML file may work better.\n");
      out.write("\n<p>The defaults for these features are to sort by weighted frequency and to display the top 50%.  For a typical text this gives a list of 100 to 300 distinct words.</p>\n\n<h3><a name=\"viewing\"></a>Viewing the Results</h3>\n<center><img src=\"/img/help/results.1.gif\"></center>\n<p>After you make your selection, the system will calculate a custom vocabulary list for your documents.  </p>\n\n");
      out.write("\n<p><a name=\"size\"></a>If you selected works through the Vocabulary Tool page, several numbers will appear at the top of your vocabulary list to help you understand general \ncharacteristics about the vocabulary of your selection.  \n\n<ul>\n<li>The <strong>number of words</strong> in your selection. </li>\n<li><a name=\"unique\"></a>The <strong>number of unique words</strong> in your selection, or the number of words that will appear on your list of if you select the \n\"All Words\" option.</li>\n<li>A <a name=\"vocabdensity\"></a><strong>vocabulary density score</strong> which is the ratio of the number of words in the document to the number of unique words in the \ndocument.</li>\n</ul>\nThese three numbers are intended to help you understand the level of vocabulary complexity in your selection.  A work with more complex vocabulary will have more \nunique words while a work with simpler vocabulary will have fewer unique words.  The vocabulary density ratio provides a normalized mechanism for this same information.  \nIf the vocabulary density ratio is small, the vocabulary is more complex; as the number increases, the text becomes easier.  Another way to think about this ratio is that \n");
      out.write("it is an expression of the number of words on average that you will encounter between every new word.  \n</p>\n<p>Compare the word counts and vocabulary density scores for <a href=\"/hopper/vocablist?works=Perseus:text:1999.01.0003&works=Perseus:text:1999.01.0005&works=Perseus:text:1999.01.0007&sort=weighted_freq&filt=50&filt_custom=&lang=greek\">Aeschylus' \n<em>Oresteia</em></a> (a name for the trilogy of <em>Agamemnon</em>, <em>Eumenides</em>, <em>Libation Bearers</em>) and <a href=\"/hopper/vocablist?works=Perseus:text:1999.01.0201&sort=weighted_freq&filt=50&filt_custom=&lang=greek\">Xenophon's \n<em>Anabasis</em></a>.  The <em>Oresteia</em> contains 19,707 words and 4,486 unique words with a vocabulary density score of 4.393.  This means that, on average, one \nout of every four words that a reader encounters will be new.  On the other hand, Xenophon's <em>Anabasis</em> contains 57,183 words with 4,007 unique words, for a \nvocabulary density score of 14.271.  The higher vocabulary density score suggests a much simpler vocabulary; on average only one in every fourteen words will be new.  \n");
      out.write("In fact, the <em>Anabasis</em> is almost three times longer than the <em>Oresteia</em> but it contains only about 2/3 as many unique words.</p>\n<p>Similarly, <a href=\"/hopper/vocablist?works=Perseus:text:1999.02.0169&sort=weighted_freq&filt=50&filt_custom=&lang=la\">Livy's <em>History</em>, books 1-10</a>, is \n159,186 words long but contains only 7,446 unique words, so its vocabulary density is 21.379.  <a href=\"/hopper/vocablist?works=Perseus:text:1999.02.0055&sort=weighted_freq&filt=50&filt_custom=&lang=la\">Virgil's \n<em>Aeneid</em></a>, less than half as long (63,719 words), uses almost as many different words (6,677 of them), giving it a vocabulary density score of only 9.543.  In other \nwords, while Livy's vocabulary is larger than Virgil's, new words do not appear as frequently.</p>\n\n<p>\n<strong><a name=\"list\"></a>The Vocabulary List</strong>: The vocabulary list will appear along with a series of numbers to give you information \nabout each word in the context of your list.  The actual contents of your list will vary based on the way that you customized the list and the sort order that you \n");
      out.write("requested.\n\n<ul>\n<li><strong>Count</strong>:  The row number is supplied to help you keep your place in the table. The count appears on every tenth row.\n<li><strong>Word</strong>:  The words in your vocabulary list are linked to the Word Study Tool, from which you can get a short definition, a link to the full lexicon \nentry, and frequency information for this word in the corpus as a whole.\n<li><strong><a name=\"freqs\">Minimum</a>, <a name=\"max\">Maximum</a>, and <a name=\"weight\">Weighted Frequencies</a></strong>:  These numbers give you a sense of how common \n  a word is in a text.  A more detailed description of the three different ways that we count words <a href=\"#wft\">is provided below</a>.  The maximum frequency, like\non other pages in Perseus, will link to a search of that word.</li>\n<li><strong><a name=\"defs\"></a>Definition</strong>:  The short definition provided is automatically extracted from various lexica in the Perseus collections.  This \ndefinition is the one listed first in the dictionary entry for each word.  Thus, the definition provided for words with multiple senses may not be entirely correct for \n");
      out.write("the works that you have selected.  If you would like to see the complete definition, you can look up the full definition in the dictionary using the Word Study Tool.\n<li><strong>Lexicon Entries</strong>: This provides you with links to the entries in our various lexica for the particular word.</li>\n<li><strong><a name=\"tfidf\"></a>Key Term Score</strong>:  As noted above, words with a high key term score appear relatively often in your selection of documents and \nrelatively infrequently in the collection as a whole.  Words with a high key-term score are an automatically extracted variety of keyword that provides an initial guide \nto important people, places, and concepts in your selection.  Frequently appearing words that provide less guidance about the contents of your selection will have a low \nkeyword score and the least important key words will have a score of 0.  ");
      out.write('\n');
      out.write("\n<br><font size=-1><strong>Note</strong>: The quality of the key words will vary based on the size and \nsimilarity of the works that you select.  As with any automatic knowledge discovery procedure, these scores might provide an interesting guide to further exploration but \nthey might not produce interesting or useful results for your selection of texts.</font>\n</ul>\n<p>\n<strong><a name=\"refine\"></a>Refining Your Word List</strong>:  To the right of your vocabulary list, you will find controls to refine your sort order, change the number of \nwords that your list contains, or, if you chose full texts, the option to select new works by language.\n\n<p><h3><a name=\"tasks\"></a>Things You Can Do with the Vocabulary Tool</h3>\n<p>The Vocabulary Tool is very versatile and it can be used in several ways to help you read a text in the Perseus Digital Library.\n\n\n<ul>\n\t<li><strong><a name=\"comp\"></a>A Comprehensive Vocabulary List for a Work</strong>:  If you want a comprehensive vocabulary list that you can consult as you read and \n");
      out.write("review a text, you should select the text that you are trying to read in the select box.  Use the alphabetical sort order and show all words for the list size.  This \nwill produce a comprehensive list of words in alphabetical order that you can annotate and consult easily as you are reading a text.</li>\n\t<li><strong><a name=\"authess\"></a>A List of Essential Words for an Author</strong>:  If you want to improve your mastery of a particular Greek or Latin author, you should \nselect all of the works by that author in the select box.  Select weighted frequency as your sort order and top 40% or top 50% as your list size option.  This will provide \nyou with a list of 'essential words' that you should memorize to maximize your understanding of that author.</li>\n\t<li><strong><a name=\"inter\"></a>A List of Basic Words for Intermediate-Level Reading</strong>:  If you are an intermediate-level student, beginning to read unadapted texts, \nselect five or six texts of interest in the select box.  Select weighted frequency as your sort order and top 50% or top 60% as your list size option.  This will give you \n");
      out.write("a sense of the most important words in the language;  when you are familar with these words, you can begin reading, confident that you will know half to two-thirds of the \nwords on a typical page.\n\t<li><strong><a name=\"compess\"></a>A List of Essential Words for a Comprehensive Greek or Latin Exam</strong>:  If you are an advanced student preparing for comprehensive \nexams, select a large list of authors that are appropriate for the requirements of your exam in the language box.  Select weighted frequency as your sort order and top \n70% or top 80% as your list size option.  This will provide you with a list of important words to help you prepare for your exam.</li>\n\t<li><strong><a name=\"keylist\"></a>A List of Key Words for a Text</strong>:  If you want a quick overview of the potentially important words and concepts in a text, select \nthe text that interests you with a sort order of key word score and a list size of top 10%.  This will provide a short list of potentially important words to be aware of \nas you read the text.</li>\n");
      out.write("</ul>\n\n    <p><li><b><a name=\"wft\">Word Frequency Tool (Greek or Latin):</a></b> If you are searching for occurrences of specific Greek or Latin words, you may use the Word Frequency Tool. There are several options for displaying results. <i>Sort Authors Alphabetically</i> is the default option. <i>Sort Authors by Type of Literature</i> will sort results according to types such as comedy, history, tragedy,etc. <i>Sort Authors by Date</i> will list authors starting from the earliest work to the latest based on the best evidence we have for each author. <i>Words in Author</i> will sort results from the author with the most words in Perseus, to the author with the fewest. <i>Maximum Instances</i> will sort results from the most possible instances in a given author; <i>Minimum Instances</i> reverses this list and starts with the fewest. <i>Maximum Frequency/10K</i> will sort the results from the highest incidence of relative frequency to the lowest; <i>Minimum Frequency/10K</i> reverses this list and begins with the lowest relative frequency.<br>\n");
      out.write("      <b><a name=\"max\">Why are there Maximum and Minimum Frequencies?</a></b> Although Perseus can disambiguate a vast majority of Greek and Latin words, there are some forms which may be derived from more than one lexicon entry. (E.g. &quot;flies&quot; may be an instance of the verb &quot;to fly&quot; <i>or </i>the noun &quot;fly&quot;, so Perseus would include it in the count for both words. On the other hand, there's no doubt that &quot;sneezed&quot; is a form of &quot;to sneeze&quot;) In cases where the maximum instances differ from the minimum, the maximum are all of the possible occurrences of a given lemma, and the minimum are all of the occurrences of the word which the computer has disambiguated. So, all ambiguous forms are included in a maximum count, and excluded from the minimum. This is also true of the relative frequency calculations.<br>\n        <b><a name=\"weight\">What is a Weighted Frequency?</a></b> A weighted frequency tells you whether the actual frequency count for a word (if this were possible) would be closer to the minimum or maximum frequency score. The weighted frequency is determined by assigning a weight to each inflected form based on the number of possible dictionary forms from which the inflected form could be derived. For example, an unambiguous word would have a weight of 1, a word that could be derived from two dictionary headwords would receive a weight of 1/2, a word that could be from 3 different headwords is given the weight of 1/3, etc. The weighted frequency is calculated as the sum of the weights for each inflected form that appears in a text. If the weighted score is equal to the average of the minimum and maximum score, you know that the word is entirely ambiguous in all of its forms. On the other hand, if the minimum, maximum, and weighted scores are all the same, you know the word is entirely <i>un</i>ambiguous in all of its forms. As the weight approaches the maximum score, it becomes more likely that the maximum count is closer to the actual count; the actual count would be greater than the weighted score and less than or equal to the maximum.<br>\n");
      out.write("          <b><a name=\"rel\">Why use relative frequencies?</a></b> Relative frequencies are based on occurrences of a given word per 10,000 words. For instance, in the case of the Greek verb <i>pemp&ocirc;</i>, Plutarch uses this verb 146 times, which is unimpressive compared with Xenophon's maximum of 350 times. Yet, the corpus of Plutarch on-line in Perseus is about 107,000 words compared with Xenophon's 312,000. So, the relative frequency in Plutarch is 13.67 at its maximum, compared with Xenophon's maximum of 11.21. When making comparisons between authors, it is most useful to know the relative frequency for a given word rather than the word count itself, since the size of the corpora vary.\n\n\n<hr>\n<i>revised  22 Feb, LMC</i>\n</div> <!-- index_main_col -->\n\t</div> <!-- content 2column -->\n</div> <!-- main -->\n\n    <!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n</body>\n</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
