package org.apache.jsp.help.archived;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fonthelp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n  <head>\n    <title>Perseus Greek Font display Help (deprecated)</title>\n    <link href=\"/css/hopper.css\" type=\"text/css\"\n    rel=\"stylesheet\"/>\n  </head>\n  <body>\n    ");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n  <div id=\"main\">\n      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("help", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("archives", request.getCharacterEncoding()), out, false);
      out.write("\n\n\t<div id=\"content\" class=\"2column\">\n\t<div id=\"index_main_col\">\n\t\t\t\t<h3> Greek Font Display Help (deprecated)</h3>\n\t\t\t\t<b>last revised: 05/31/05</b><br>\n\t\t\t\t<ol>\n\t\t\t<li><b><a href=\"#basics\">The basics: reading versus entering polytonic Greek.</a></b>\n\t\t\t<li><b><a href=\"#advantages\">Advantages and disadvantages of the Perseus Greek display options.</a></b>\n\t\t\t<li><b><a href=\"#best\">Which polytonic Greek font is best for me?</a></b>\n\t\t\t<li><b><a href=\"#change\">How to change the Greek display.</a></b>\n\t\t\t<li><b><a href=\"#other\">Other notes.</a></b>\n\t\t</ol>\n\t\t\t\t<ol>\n\t\t\t<li><a name=\"basics\"></a><b>The basics: reading versus entering polytonic Greek.<br>\n\t\t\t\t</b>The font options we provide apply only to the <i>display</i> of Greek texts. Any tool in which you must enter Greek will still display your entry in a Latin font. There are several options for representing the Greek letters (just as for displaying texts), but you will always see the Roman alphabet in the resulting search box. When searching for dictionary headwords, using the Greek morphological analysis, or searching on Greek words in context, you must transliterate your Greek letters and accents based on one of the Perseus Greek options. You cannot, at this time, copy and paste Greek from another program or site, or type it using a Greek font.<font size=\"-1\"> (The Enter Text in Greek keyboard tool permits clicking on the Greek letters and accents, and then converts the result into the appropriate Latin characters based on user settings, but can give erratic results.)<br>\n");
      out.write("\t\t\t\t</font>Most Greek searching errors occur with incorrect transliteration of Greek letters.\n\n\t\t\t<li><a name=\"advantages\"></a><b>Advantages and disadvantages of the Perseus Greek display options.<br>\n\t\t\t\t</b>\n\t\t\t<table width=\"602\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\" height=\"180\">\n\t\t\t\t<tr height=\"20\">\n\t\t\t\t\t<td width=\"130\" height=\"20\"><b>Option</b></td>\n\t\t\t\t\t<td width=\"200\" height=\"20\"><b>Advantages</b></td>\n\t\t\t\t\t<td width=\"260\" height=\"20\"><b>Disadvantages</b></td>\n\t\t\t\t\t<td width=\"260\" height=\"20\"><b>Sample</b></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">Latin transliteration</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">no special font required<br>\n\t\t\t\t\t\t\tworks on any browser<br>\n\t\t\t\t\t\t\tdefault setting</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">doesn't look like Greek; can be hard to read</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01latintrans.png\" alt=\"\" height=\"13\" width=\"231\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">Greek transliteration</font></td>\n");
      out.write("\t\t\t\t\t<td width=\"200\"><font size=\"-1\">no special font required<br>\n\t\t\t\t\t\t\tworks on any browser<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">doesn't look like Greek; can be hard to read<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01greektrans.png\" alt=\"\" height=\"13\" width=\"232\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">GreekKeys</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">looks like Greek<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">requires font installation<br>\n\t\t\t\t\t\t\tmay not display properly on every browser<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01greekkeys.png\" alt=\"\" height=\"17\" width=\"250\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">SGreek for Windows</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">looks like Greek<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">requires font installation<br>\n");
      out.write("\t\t\t\t\t\t\tmay not display properly on every browser<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01Sgreek.png\" alt=\"\" height=\"18\" width=\"340\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">SP Ionic</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">looks like Greek<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">requires font installation<br>\n\t\t\t\t\t\t\tmay not display properly on every browser<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01SPionic.png\" alt=\"\" height=\"18\" width=\"246\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">Super Greek</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">looks like Greek<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">requires font installation<br>\n\t\t\t\t\t\t\tmay not display properly on every browser<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01supergreek.png\" alt=\"\" height=\"16\" width=\"259\" border=\"0\"></td>\n");
      out.write("\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">Beta Code</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">no special font required<br>\n\t\t\t\t\t\t\tworks on any browser<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">doesn't look like Greek; can be hard to read<br>\n\t\t\t\t\t\t\tmust change configuration to select this option<br>\n\t\t\t\t\t\t</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01betacode.png\" alt=\"\" height=\"16\" width=\"287\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"130\"><font size=\"-1\">Unicode</font></td>\n\t\t\t\t\t<td width=\"200\"><font size=\"-1\">looks like Greek<br>\n\t\t\t\t\t\t\tmost operating systems have fonts pre-installed<br>\n\t\t\t\t\t\t\tfonts freely available and well documented</font></td>\n\t\t\t\t\t<td width=\"260\"><font size=\"-1\">may require font installation<br>\n\t\t\t\t\t\t\tmay not display properly on every browser<br>\n\t\t\t\t\t\t\tmust change configuration to select this option</font></td>\n\t\t\t\t\t<td width=\"260\"><img src=\"/img/help/01unicodeplain.png\" alt=\"\" height=\"15\" width=\"317\" border=\"0\"><br>\n\t\t\t\t\t\t<img src=\"/img/help/01unicode.png\" alt=\"\" height=\"17\" width=\"289\" border=\"0\"><br>\n");
      out.write("\t\t\t\t\t\t<img src=\"/img/help/01Unicodewin.png\" alt=\"\" height=\"20\" width=\"251\" border=\"0\"></td>\n\t\t\t\t</tr>\n\t\t\t</table>\n\t\t\t<li><a name=\"best\"></a><b>Which polytonic Greek font is best for me?</b><br>\n\t\t\t\t<b>Windows (tested on XP, SP2)</b>\n\t\t\t<table width=\"570\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><b>Polytonic Font</b></td>\n\t\t\t\t\t<td width=\"133\"><b>Internet Explorer</b></td>\n\t\t\t\t\t<td width=\"191\"><b>Firefox</b></td>\n\t\t\t\t\t<td width=\"84\"><b>Netscape</b></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr height=\"16\">\n\t\t\t\t\t<td width=\"150\" height=\"16\"><font size=\"-1\">GreekKeys</font></td>\n\t\t\t\t\t<td width=\"133\" height=\"16\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"191\" height=\"16\"><font size=\"-1\">some letter combos do not display</font></td>\n\t\t\t\t\t<td width=\"84\" height=\"16\"><font size=\"-1\">works well</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">SGreek</font></td>\n\t\t\t\t\t<td width=\"133\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"191\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"84\"><font size=\"-1\">works well</font></td>\n");
      out.write("\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">SP Ionic</font></td>\n\t\t\t\t\t<td width=\"133\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"191\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"84\"><font size=\"-1\">works well</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Super Greek</font></td>\n\t\t\t\t\t<td width=\"133\"><font size=\"-1\">N/A: Mac font</font></td>\n\t\t\t\t\t<td width=\"191\"><font size=\"-1\">N/A: Mac font</font></td>\n\t\t\t\t\t<td width=\"84\"><font size=\"-1\">N/A: Mac font</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Unicode</font></td>\n\t\t\t\t\t<td width=\"133\"><font size=\"-1\">incomplete characters</font></td>\n\t\t\t\t\t<td width=\"191\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"84\"><font size=\"-1\">works well</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Unicode with precombined</font></td>\n\t\t\t\t\t<td width=\"133\"><font size=\"-1\">incomplete characters</font></td>\n\t\t\t\t\t<td width=\"191\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"84\"><font size=\"-1\">works well</font></td>\n");
      out.write("\t\t\t\t</tr>\n\t\t\t</table>\n\t\t\t<b>Macintosh (tested on OS X 10.3.6)</b>\n\t\t\t<table width=\"724\" border=\"1\" cellspacing=\"0\" cellpadding=\"0\">\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><b>Polytonic Font</b></td>\n\t\t\t\t\t<td width=\"140\"><b>Safari</b></td>\n\t\t\t\t\t<td width=\"140\"><b>Internet Explorer</b></td>\n\t\t\t\t\t<td width=\"140\"><b>Firefox</b></td>\n\t\t\t\t\t<td width=\"140\"><b>Netscape</b></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr height=\"16\">\n\t\t\t\t\t<td width=\"150\" height=\"16\"><font size=\"-1\">GreekKeys</font></td>\n\t\t\t\t\t<td width=\"140\" height=\"16\"><font size=\"-1\">encoding must be Western (Mac OS); spacing issues</font></td>\n\t\t\t\t\t<td width=\"140\" height=\"16\"><font size=\"-1\">doesn't work</font></td>\n\t\t\t\t\t<td width=\"140\" height=\"16\"><font size=\"-1\">encoding must be set as Western (MacRoman)</font></td>\n\t\t\t\t\t<td width=\"140\" height=\"16\"><font size=\"-1\">encoding must be set as Western (MacRoman)</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">SGreek*</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">doesn't work*</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well*</font></td>\n");
      out.write("\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well*</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well*</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">SP Ionic</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Super Greek</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works well</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Unicode</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; accents displayed apart from characters</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">doesn't work</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; accents displayed apart from characters</font></td>\n");
      out.write("\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; accents displayed apart from characters</font></td>\n\t\t\t\t</tr>\n\t\t\t\t<tr>\n\t\t\t\t\t<td width=\"150\"><font size=\"-1\">Unicode with precombined</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; some combination characters do not display</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">doesn't work</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; some combination characters do not display</font></td>\n\t\t\t\t\t<td width=\"140\"><font size=\"-1\">works; some combination characters do not display</font></td>\n\t\t\t\t</tr>\n\t\t\t</table>\n\t\t\t<font size=\"-1\">* SGreek is a Windows font, but this filter still works on the Mac. It is not clear if any particular font installation is required or if this is simply an unexpected feature.</font>\n\t\t\t<li><a name=\"change\"></a><b>How to change the Greek display.<br>\n\t\t\t\t</b>a. If needed, <b>install</b> your chosen font:<br>\n\t\t\t\t<i>GreekKeys</i>. For display of texts in Perseus, we offer an older version of GreekKeys Athenian free of charge, as does the <a href=\"http://socrates.berkeley.edu/%7epinax/greekkeys/Atheniandownload.html\">GreekKeys support site</a>. Please contact the webmaster for more information. (webmaster@perseus.tufts.edu)<br>\n");
      out.write("\t\t\t\t<i>SGreek. </i>This is a shareware font offered by <a href=\"http://www.silvermnt.com/fonts.htm\">Silver Mountain Software</a>.<br>\n\t\t\t\t<i>SP Ionic.</i> Available on various sites, including <a href=\"http://www.monachos.net/other/fonts/get_greek_font.shtml\">Monachos.net</a>.\n<br>\n\t\t\t\t<i>SuperGreek. </i>Not currently available. An older version of a font package offered by <a href=\"http://www.linguistsoftware.com\">Linguist Software</a>. A broader WWW search may turn up some older versions of this font, or write to the webmaster for further advice.<br>\n\t\t\t\t<i>Unicode</i>. For Windows, most current versions of the operating system include Lucida Sans Unicode. (You may use any Unicode font that includes <b>both</b> the Greek letters (the &quot;Basic Greek&quot; Unicode subset) <b>and</b> the accent marks (the &quot;Combining Diacriticals&quot; Unicode subset). If your font does not include both of these subsets, Perseus Greek texts will not display correctly). For the Mac, please consult the <a href=\"http://socrates.berkeley.edu/%7epinax/greekkeys/GreekKeys.html\">GreekKeys support site</a>, which offers excellent GreekKeys Unicode font options.<br>\n");
      out.write("\t\t\t\t<br>\n\t\t\t\tb. Open a Greek text, either by selecting it from the table of contents or by changing the English version to a Greek version.<br>\n\t\t\t\t<br>\n\t\t\t\tc. Follow the &quot;Configure Display&quot; link at the top of the page, typically found in the navigation bar. In the section labeled Greek display, choose your font configuration. (You may also change any other options on this page). Select the &quot;Set Configuration&quot; button at the top of the page and you will be returned to the text page automatically.<br>\n\t\t\t\t<br>d. If the display is not correct, you may have to manually change some other settings. For instance, the font preferences for &quot;user defined&quot; fonts may have to be changed, or the text encoding may need to be altered. In most cases, with a recent browser and a newer operating system, this will not be necessary. In particular, check the accessibility options: on some configurations you do not want to ignore the page-specified font styles. Most errors occur when the font is not properly installed. If you cannot see the Greek text, please write to the webmaster (webmaster@perseus.tufts.edu) with as much detail about the problem as possible. Please include your operating system version and browser type and version so that we may attempt to replicate the problem here.<br>\n");
      out.write("\t\t\t\t<br>\n\t\t\t\n\t\t\t\n\t\t\t<li><a name=\"other\"></a><b>Other notes: <br>\n\t\t\t\t\tLinux with X Windows:</b> You can use any of the TrueType fonts supported for Microsoft Windows. Install the font and configure your X font server to recognize it; we have found that it is essential to set the font's encoding to ISO-8859-1 whether or not that is really correct for the font. Once you have done this, you can use your TrueType font with Perseus or any other site that uses the Perseus font system. We have tested this with RedHat Linux 6.2, 7.0, and 7.1 using Netscape 4.7. We expect that the same method will work with other X Windows implementations on other versions of Unix, but we have not tested them and cannot provide support.\n<br>\n\t\t\t\t<br>\n\t\t\t\tFor further information about Unicode and Greek, see the Stoa Consortium's <a href=http://www.stoa.org/unicode/>Unicode Polytonic Greek for the World Wide Web,</a> by Patrick Rourke; you will need a Unicode font to read it properly.<br>\n\t\t\t\t<br>\n\t\t\t\t<font size=\"-1\"><b>A note on fonts in Perseus.</b><br>\n");
      out.write("\t\t\t\t</font><font size=\"-1\">Ancient Greek works in Perseus are stored as beta code, a standard way of describing Greek letters and accents using basic ASCII characters. In order to provide better reading options for the texts we provide, Perseus developed a filter which converts this beta code into other font displays. For many years, browser technology made it a challenge to present more than one font on a WWW page. Perseus purposefully avoided using extensive scripting which might make the site too slow for most of our users; our current font display system is, therefore, imperfect and limited. </font>\t\t</ol>\n\t\t\t\t<i>document revised</i> May, 2005 LMC \n\n</div> <!-- index_main_col -->\n\t</div> <!-- content 2column -->\n</div> <!-- main -->\n\n    <!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n</body>\n</html>\n\n\n\n\n\t\n\n\n\n\n\n\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
