package org.apache.jsp.help.archived;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class oldfaq_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n  <head>\n    <title>Perseus FAQ (deprecated)</title>\n    <link href=\"/css/hopper.css\" type=\"text/css\" rel=\"stylesheet\"/>\n  </head>\n  <body>\n    ");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n  <div id=\"main\">\n      ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("help", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("archives", request.getCharacterEncoding()), out, false);
      out.write("\n\n  <div id=\"content\" class=\"2column\">\n      <div id =\"index_main_col\">\n      <H3>The Perseus WWW Frequently Asked Questions List (deprecated)</H3>\n\tcreated: 1/12/98<br>\n\t<b>last revised: 10/6/05</b><br>\n\tsee the <a href=\"/help/faq.html\">updated version of this document</a>\n\t<P>\n\tThis list is a summary of the most frequently asked questions\n      received by the Perseus <A HREF=\"mailto:webmaster@perseus.tufts.edu\">webmaster</A>.  If the\n      answer to your question is not here, please <a href=\"mailto:webmaster@perseus.tufts.edu\">e-mail us</a>.\n\t\n\t<ol>\n\t<p><B>About Perseus</B><br>\n\t<li><a href=\"#whatis\">What is the Perseus Digital Library Project?</a>\n\t<li><a href=\"#free\">Is this site free?</a>\n\t<p><B>General Questions</B>\n\t<li><a href=\"#start\">Where do I start?</a>\n\t<li><A HREF=\"#info\">How do I find something in Perseus? What types of searches can I do?</A>\n\t<li><A HREF=\"#word\">How do I find the meaning of this Greek or Latin word?  My searches aren't returning any results.</A>\n\t<li><A HREF=\"#trans\">What is the (Greek/Latin/English) translation of this phrase?</A>\n");
      out.write("\t<li><A HREF=\"#paper\">Will you help me with my project or paper?</A>\n\t<li><A HREF=\"#mail\">Why do I receive an automatic reply to a webmaster question?</A>\n\n\t<P><B>Images</B>\n\t<li><A HREF=\"#permiss\">Why does it say that I do not have permission to view the image I want to see and how do I get permission?</A>\n\t<li><A HREF=\"#copy\">I would like a copy of one of the images I've seen in Perseus.  How do I get one?</A>\n\t<P><B>Texts & Fonts</B>\n\t<li><A HREF=\"#text\">Why don't you have a particular text?</A>\n\t<li><A HREF=\"#scroll\">How can I download a complete text file?</A>\n\t<li><A HREF=\"#font\">I'm having trouble viewing the Greek with the Greek fonts.  What should I do?</A>\n\t<li><a href=\"#unicode\">Why do I see wacky question marks or boxes in the middle of Latin words?</a>\n\t<li><A HREF=\"#typo\">Where do I report a typo? What if I disagree with your translation?</A>\n\t<li><a href=\"#hopper\">What are the advantages of the Perseus text system?</a>\n\t</ol>\n\t\t\n\t<hr>\n\t<ol>\n\t<li><a name=\"whatis\"><b>What is the Perseus Project?</b></a>\n");
      out.write("\t<p>The Perseus Project is an evolving digital library of resources for the study of the humanities. We are funded to perform research on developing tools to provide users with improved access to various types of materials. Past work has focused on building and linking together collections. Current work considers ways of developing and refining tools for presentation of the materials in the Perseus DL. We are primarily a research project, although we do incorporate services for our audience. For more on who we are and what we do, see the <a href=\"/PerseusInfo.html\">About Perseus page</a>, our list of <a href=\"/Articles/index.html\">publications</a>, and information on our<a href=\"/collab.html\"> collaborations</a>.</p>\n\t<hr>\n\t<li><a name=\"free\"><b>Is this site free?</b></a>\n\t<p>Currently, we offer access to materials free of charge, with the exception of certain copyrighted images, <a href=\"#permiss\">noted below</a>. As we explain elsewhere, we are not funded to provide services, but to do research on how people use these materials and how use may be improved or refined. We offer no warranty on use, as outlined <a href=\"/site.html\">here</a>. Although portions of the data may be derived from public domain materials, the Perseus Project has created tools and structure to link this data to the remainder of the library. Please see <a href=\"/copyright.html\">copyright information</a> for more on rights and right holders, and consider <a href=\"/support.html\">supporting Perseus</a> with a donation. </p>\n");
      out.write("\t\t\n\t<hr>\n\t<li><a name=\"start\"><b>Where do I start?</b></a>\n\t<p>There are many ways of accessing the materials in the Perseus digital library. In fact, there is more than one way of getting to the core content of the digital library. <br>\n\t<div align=\"center\"><img src=\"/img/help/navigate.gif\"><br><font size=\"-1\">Multiple ways of getting to core Perseus contents.<br>(Or, there's more than one way to slay a Gorgon!)</font></div>Clearly, there are many ways you can begin exploring Perseus content. Which one best suits your particular needs? The answer to that question typically depends on the type of information you require. Read on for more information.<br>\n\t\t\t\n\t<hr>\n\t<li><B><A NAME=\"info\">How do I find something in Perseus? What types of searches can I do?</A></B>\n\t<P> The Perseus digital library contains a\nwealth of information but new users can have trouble accessing it all.\nWe at the project are committed to providing resources and tools to\nuse these resources to as many people as possible.  We are not,\nhowever, a research service and we cannot answer specific questions or\n");
      out.write("perform customized searches for information.  We encourage users to\ncontinue to make use of local libraries and librarians when doing\nresearch projects.<P> Here are some general suggestions to help\nintroduce you to the way that the Perseus library is set up:<P> <A\nNAME=\"lookup\"><B>Start </B></A><B>with the <A HREF=\"/cgi-bin/vor\">Perseus lookup\ntool</A>.</B> The lookup tool is a map to the contents of Perseus: its results point you to the subject areas in which you will find information about your search topic. It is a guide to information within Perseus; you the user must decide which type of information suits your interest, but be aware that for certain types of inquiries, you may need another tool. The input box for the lookup tool is beneath the &quot;Search&quot; icon on the home page next to the banner image and on every other page in the same general location. You need only type your query in the input box and click the &quot;Search,&quot; or the &quot;return&quot; or &quot;enter&quot; key. <!--For more information on the lookup tool, and some sample searches, see <a href=\"VorHelp.html\">the lookup tool help page.--></a>\n");
      out.write("\t\t\t\n\t<HR>\n\t<li><B><A NAME=\"word\">How do I find the meaning of this Greek or Latin word?  My searches aren't returning any results.</A></B><P>If you are a Greek or Latin novice and trying to translate a word or phrase, check our <a href=\"trans.html\">Greek and Latin translation tips.</a>\n\t<p>First, check that you're using the correct tool; neither the lookup tool nor the English index will find Greek or Latin words. Second, you should check that your Greek or Latin word is properly spelled and transliterated. While the <A HREF=\"#lookup\">Perseus Lookup Tool</A> mentioned above helps you find alternative spellings for various English terms, you must be <B>precise</B> when searching for Greek or Latin words.  For example, if you are searching for a Greek term in the original Greek, be certain that you are transliterating the letters according to the Perseus transliteration system: <br>\n\t</p>\n\t<CENTER><IMG SRC=\"/img/help/latin.gif\"></CENTER><br>(The term \"catharsis\" actually begins with a kappa in Greek, so while a search for \"catharsis\" in the Greek lexicon will show no results, a search for \"<A HREF=\"/cgi-bin/resolveform?lookup=katharsis&type=begin&author=*2.0&options=Sort+Results+Alphabetically&.submit=Submit+Query&formentry=1&lang=Greek\">katharsis</A>\" will.)  Each page that calls for transliteration has a chart with the correct character matches.<P>\n");
      out.write("A majority of Greek or Latin searching errors occur when a form other than the basic, uninflected form has been entered.   You must be certain that the word for which you are searching is the <B>correct root form</B>, or else your results will be non-existent or incomplete.  Just as you can't check an English dictionary for \"swam,\" and you must look up the basic form of the word, \"swim,\" you can't check the Greek and Latin lexica for inflected forms of Greek and Latin words.  For example, \"ave\" (as in \"Ave, Maria\") is a Latin word, but a search for \"ave\" will fail.  You must search for the root form of \"ave\" which is \"<A HREF=\"/cgi-bin/lexindex?lookup=aveo%232&lang=Latin&corpus=Roman&display=\">aveo</A>.\"  If you are uncertain about the form of the word for which you are searching, you may want to first use the morphological analysis tool for <A HREF=\"/cgi-bin/morphindex?lang=Greek&corpus=2.0&display=Latin+transliteration\">Greek</A> or <A HREF=\"/cgi-bin/morphindex?lang=Latin\">Latin</A>.  This will tell you the correct root of the word, or at least help narrow your search.  <A HREF=\"/cgi-bin/morphindex?lookup=ave&.submit=Analyze+Form&lang=Latin&corpus=Roman&author=&formentry=1\">An example of an analysis of the above Latin word \"ave\" is here.</A>  Note that the morphological analysis <B>does not \"disambiguate\" forms:</B>  the Latin word \"ave\" could be derived from one of three root words.  The reader must choose which of the three best fits the context of the word.\n");
      out.write("\t<P>Searches of the Greek and Latin lexica are <B>single word searches only</B>, as are Greek and Latin word searches.  Remember, that common Greek terms have often been \"Latinized\" when they enter English, so double check them before attempting a search in Greek.\n\n\t<p><img src=\"/img/help/comptoolchart.gif\" alt=\"\" height=\"238\" width=\"776\" border=\"0\"></p>\n\t<HR>\n\t<li><b><a name=\"trans\">What is the (Greek/Latin/English) translation of this phrase?</a></b>\n\t<P>If you are a Greek or Latin novice and trying to translate a word or phrase, check our <a href=\"trans.html\">Greek and Latin translation tips.</a>\n\t<p>\nUnfortunately, the Perseus Project does not have the staff or resources to perform custom translation services.  There are many sites with translations of common phrases.  Here is one such site with <A HREF=\"http://en.wikipedia.org/wiki/List_of_Latin_phrases\">Latin phrases</A>. This is a site which <A HREF=\"http://www.users.globalnet.co.uk/~loxias/search.htm\">welcomes translation inquiries</A> for Latin and some Greek. If you are learning Greek and/or Latin, you may wish to visit the forum page at <a href=\"http://www.textkit.com\">Textkit - Greek and Latin Learning Tools</a>.<br>\n");
      out.write("\t\t\t\t\n\t\t\t\t\nHere are some of the most commonly asked about phrases (please don't e-mail us about these!):\n</p>\n\t\t\t<UL><li><B>illegitimus non carborundum</B> (comes in many variations):  this is pseudo-Latin;  check the <A HREF=\"http://lsv.uky.edu/archives/classics-l.html\">classics list archives for more information.</A>\n<LI><B>Lorem ipsum dolor sit amet</B>, . . .. :  it looks like Latin, but it's nonsense. This is the filler text used to demonstrate printing layouts which came into use not long after the printing press itself; it persists in  software manuals to this day. It's believed to be a bastardization of some Cicero.  Check the <A HREF=\"http://lsv.uky.edu/archives/classics-l.html\">classics list archives for more information.</A>\n<LI><B>uva uvum (or uvam) vivendo varia fit</B> from <I>Lonesome Dove.</I> Again, an instance of imperfect Latin. <A HREF=\"http://www.library.txstate.edu/swwc/ld/ldex081a1.html\">Check this wonderful WWW page</A> for insight into the translation debate.\n</ul>\n<HR>\n<li><B><A NAME=\"paper\">Will you help me with my project or paper?</A></B><P>\n");
      out.write("The Perseus Project is not a research service and we do not have the staff or resources to fulfill all of the requests we receive for assistance.  We will gladly assist our users in searching the Perseus digital library, but we cannot answer specific research questions or direct you to relevant sites or bibliography. <P>Some good starting points are <a href=\"http://en.wikipedia.org/wiki/Main_Page\">Wikipedia</a>, <a href=\"http://about.com/\">About.com</a>,  <a href=\"http://www.google.com/\">Google</a>, and <A HREF=\"http://www.yahoo.com\">Yahoo!</A>.<HR>\n<li><B><A NAME=\"mail\">Why do I receive an automatic reply to a webmaster question?</A></B><P>\nWe receive an average of 20 mails to the webmaster each day; over 100 per week. This number is always increasing.  A majority of these queries are answered here in the FAQ or elsewhere (<A HREF=\"/Help/\">other help pages</A>, the <A HREF=\"/copyright.html\">copyright page</A>, <A HREF=\"/PerseusInfo.html\">About Perseus</A>, etc.). In order to dedicate our limited resources to the questions pertaining to use of the Perseus Digital Library, we have reluctantly instituted the automatic reply. Be aware that <B>if you write from one e-mail address and request an answer at another, you may not receive a reply. </B> (The automatic reply contains suggestions for other WWW sites of interest and links to pertinent parts of Perseus.) <P>\n");
      out.write("We also want to stress that all mail received at Perseus is not only read, but also logged into a webmaster database of incoming mail.  We sincerely appreciate your comments, praise, and suggestions for improvement; unfortunately, we won't always be able to tell you so in a personal reply. All reports of errors are investigated promptly.<P>\n<B>Some tips on receiving a prompt, personal reply:</B> 1) Send your mail in complete sentences, not single words or phrases. We can't guess what your question is, so give as much information as possible. Also, if you are reporting a problem, include a copy of the relevant  URL(s). 2) Try not to use words like \"urgent\" or include deadlines: our mail, when answered, is answered within five business days and in the order it is received.  We don't prioritize answers, respond on the weekends, or guarantee a reply. To that end.... 3) Do not send homework questions.  We will help you use Perseus to find an answer: we do not send out the answer.  If you ask an obvious homework question, you will <B>not</B> receive a reply.  If you ask for help using Perseus, you will. 4) Make your criticism constructive.  General comments are good, but if you have a problem with Perseus <B>be specific</B>. If you want to know why we do (or don't do) something, we'll tell you. Just ask!  Be considerate of the webmaster and write only mail you would like to receive. 5) Do not use all uppercase letters: in most circles, this is considered bad \"Netiquette\" and conveys a sense of urgency (see item 2 above) or shouting. No one likes to be shouted at! <p><B>Remember the more information you give us, the better equipped we are to answer you quickly, accurately and completely!</B>\n");
      out.write("\n<HR>\n<li><B><A NAME=\"permiss\">Why</A>\n<A NAME=\"sculpt\">does it say that I do not have permission\nto view the image I want to see and how do I get permission?</A></B>\n<P>\nMany of the <A HREF=\"/art&arch.html\">art\nand archaeology</A> objects in the Perseus digital library are owned\nby museums.  Perseus <A\nHREF=\"/copyright.html\">does not have\npermission</A> to display all of the images of these objects on the WWW. Currently, we provide images from the following:<ul>\n<li>all of the images in the\n<A\nHREF=\"/cgi-bin/browser?object=building\">architecture</A>\nand <A\nHREF=\"/cgi-bin/browser?object=site\">site</A>\ncatalogs; \n<li>the sculpture collections from the<ul>\n<li><a\nhref=\"/cgi-bin/browser?object=Sculpture&field=Collection&value=Museum+of+Fine+Arts,+Boston\">Museum\nof Fine Arts, Boston</a>, <li>the <a\nhref=\"/cgi-bin/browser?object=Sculpture&field=Collection&value=Berlin,+Antikenmuseen\">Berlin\nAntikenmuseen</a>, and <li>the <a\nhref=\"/cgi-bin/browser?object=Sculpture&field=Collection&value=Paris,+Mus%26eacute;e+du+Louvre\">Mus&eacute;e du Louvre, Paris</a>;\n");
      out.write("</ul><li><A\nHREF=\"/cgi-bin/browser?object=Coin&field=Collection&value=Arthur+S.+Dewing+Collection\">the\nDewing coin collection</A>;\n<li>and vase collections from the\n<ul>\n<li><a\nhref=\"/cgi-bin/browser?object=Vase&field=Collection&value=Berlin,+Antikenmuseen\">Berlin\nAntikenmuseen</a>,\n<li><a\nhref=\"/cgi-bin/browser?object=vases&field=Collection&value=Paris,+Mus%26eacute;e+du+Louvre\">Mus&eacute;e du Louvre, Paris</a>,<li><A\nHREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=Museum+of+Fine+Arts,+Boston\">Museum\nof Fine Arts, Boston</A>, \n<li><A\nHREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=Cambridge,+Harvard+University+Art+Museums\">Harvard\nUniversity Art Museums</A>,\n<li><A HREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=University+Museums,+University+of+Mississippi\n\">University of Mississippi</A>,\n<li><A\nHREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=University+Museum,+University+of+Pennsylvania\">University\nof Pennsylvania</A>,\n<li><A\nHREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=Museum+of+Art,+Rhode+Island+School+of+Design\">Rhode\n");
      out.write("Island School of Design</A>,\n<li><A\nHREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=Tampa+Museum+of+Art\">Tampa\nMuseum of Art</A> and\n<li><A HREF=\"/cgi-bin/browser?object=Vase&field=Collection&value=Toledo+Museum+of+Art\n\">Toledo Museum of Art</A>.\n</ul>\n</ul>\n<HR>\n<li><B><A NAME=\"copy\">I would like a copy of one of the images I've seen in Perseus, how do I get one?</A></B><P>\nThe credit notices for all images appear at the top of each image page.  If this notice reads \"...courtesy of X museum,\" you must contact the named museum for permission to reproduce their image.  Addresses for museums are at the bottom of our <A HREF=\"/copyright.html\">copyright page</A>. <p>The Perseus Project does not have permission or resources to redistribute images. No image contained in the Perseus digital library may be reproduced in any form without permission of the copyright holders. We cannot authorize reuse of Perseus images on other WWW sites, even for educational, non-profit use. If you have further questions about images, <A HREF=\"mailto:webmaster@perseus.tufts.edu\">please contact us</A>.\n");
      out.write("\n<HR>\n<li><B><A NAME=\"text\">Why don't you have a particular text?</A></B><P>\nThe Perseus Project's initial focus was the ancient Greek world.  Subsequent growth of the library into the Roman era and the Renaissance, including the works of Christopher Marlowe, has been a gradual process. Since we are a grant-funded project, we have limited resources at our disposal. If you have suggestions for future work, please let us know. We log all suggestions for future expansion.\n\n\n<HR>\n<li><B><A NAME=\"scroll\">How can I download a complete text file?</A></B><P>\nOur <A HREF=\"/copyright.html\">copyright</A> agreements with the publishers of our texts do not permit us to offer full text downloading at this time.  We realize that users with slower connections or those who prefer reading texts off of a hard copy, not the computer screen, would prefer a downloading option.  Hopefully, we will be able to soon provide such a service.  The addresses for the publishers of the texts are provided on our <a href=\"/copyright.html\">copyright page</a> if our readers wish to purchase the books. We also provide direct links to <a href=\"http://www.amazon.com\">amazon.com</a> on the bottom of nearly every page of text. For learning Greek and/or Latin, <a href=\"http://www.textkit.com\">Textkit - Greek and Latin Learning Tools</a> is a fine site with many texts in downloadable .pdf format.\n");
      out.write("\t\t\t<HR>\n<li><B><A NAME=\"font\">I'm having trouble viewing the Greek with the Greek fonts.  What should I do?</A></B>\n\t\t\t<P>\nFirst, check our <A HREF=\"/Help/fonthelp.html\">font help page</A> for more information on the many options for viewing Greek. This page contains important instructions, information, and notices of known font &quot;bugs.&quot; Please follow all of the steps outlined on these pages before contacting us with your questions. Also note that these instructions are subject to change, so if you have used fonts in the past but they are not working now, check the updated instructions. If you are having difficulty installing fonts, please check your user manual or ask your local technical advisor. The Perseus Project does not have the staff to answer font installation questions. Perseus provides some fonts for reading texts: you may not be able to use these fonts to type Greek characters.\n\t\t\t<hr>\n\t\t\t<li><a name=\"unicode\"><b>Why do I see wacky question marks or boxes in the middle of Latin words?</b></a>\n");
      out.write("\t\t\t<p>This is a problem with Unicode display on some browsers and platforms. Not all browsers are able to correctly map Unicode characters. You'll most likely encounter this problem with macrons appearing in Latin words (such as in the Latin grammar or Latin dictionaries). If your system should be able to read Unicode (Windows running IE), make sure you have followed the steps in the <a href=\"/Help/fonthelp.html\">font display help section</a>. Also, double check that your browser is accepting cookies.</p>\n\t\t\t<p>If you are using another system, such as a Mac, we suggest changing the way your display is configured to read Greek. (This sounds counter-intuitive for reading Latin!) Recent testing on a Mac eliminated the question marks by setting the Greek display to SuperGreek on both IE and Netscape. (NB: Netscape 4.75 was tested, not Netscape 6.) Again, be sure that you are accepting cookies. You need not install SuperGreek for this to work. The macrons will appear as circumflex accents, not macrons, but you may find this less troublesome to view. Tips on configuring your display are linked from the <a href=\"/Help/TextHelp.html#display\">text help section</a>.</p>\n");
      out.write("\t\t\t<HR>\n\t\t\t<LI><B><A NAME=\"typo\">Where do I report a typo? What if I disagree with your translation?</A></B><P>\nAt this time, all reports of typographical errors should be sent to the Perseus <A HREF=\"mailto:webmaster@perseus.tufts.edu\">webmaster</A>. Please provide the exact text citation. We rely on our users to bring these to our attention, and welcome all reports. These will be logged and investigated. In the case of variant readings, Perseus follows the original print edition of the on-line text.<P><b>Perseus does not translate works.</b> You may disagree with the translation of a work provided in Perseus; this is to be expected. Keep in mind, however, that Perseus is a digital library and we are not the authors of the translations in the digital library, no more than your local librarian is the author of every book in his or her library. (!) \n\t\t\t<p><b>Perseus does not alter the content of a print work</b> when it is converted to an electronic version except to regularize spelling and remove archaisms. In some rare cases, we have entered older source materials which may contain outdated information which has been superseded by recent research. Always check the publication date on materials. We have made an effort to provide as many materials as possible, and in doing so, we have had to rely on older, public domain sources.</p>\n");
      out.write("\t\t\t<li><a name=\"hopper\"><b>What are the advantages of the Perseus text system?</b></a>\n\t\t\t\t<p>We implemented the current version of the text system in response to user comments and suggestions. First, users had trouble finding texts and works within Perseus. The new <a href=\"/cgi-bin/perscoll\">Perseus table of contents page</a> shows you all of the contents of Perseus at once. You may customize this listing for specific collections and/or languages. This is done automatically now, and not on a static page. This means that the contents are always up-to-date. The basis of this system is a new and improved means of easily adding texts to the Perseus digital library, following the example of Perseus images. Second, users requested more display options, such as a &quot;cookie&quot; for preserving display options and the choice of the default text language. Third, navigation within a text was not intuitive. We now have a go to navigation box, a navigation bar, and arrows within every text. This helps you find a specific passage more quickly and see your relative location within a text. Fourth, we improved the searching tools, added new texts and commentaries, and added new features such automatic text links to the new <a href=\"/cgi-bin/patlas\">Perseus Atlas</a> and cross reference links. Beneath it all, we more than doubled our processor power for WWW service. This new system means we will be better able to deliver future additions to the Perseus Digital Library. So, check the <a href=\"/Help/tochelp.html\">table of contents help page</a> and the <a href=\"/Help/TextHelp.html\">updated text help page</a> and try it out!</p>\n");
      out.write("\t\t\t</ol>\n\n\t</div> <!-- index_main_col -->\n\t</div> <!-- content 2column -->\n</div> <!-- main -->\n\n    <!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n</body>\n</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
