package perseus.voting;
// Generated Feb 5, 2007 12:18:58 PM by Hibernate Tools 3.2.0.beta8


import java.util.Date;

import perseus.ie.entity.AbstractEntity;
import perseus.ie.entity.Entity;
import perseus.ie.entity.EntityOccurrence;

/**
 * Vote generated by hbm2java
 */
public class Vote<T extends Entity> implements java.io.Serializable {
    private static final long serialVersionUID = 1L;

    public static final Entity NONE_OF_THE_ABOVE = new AbstractEntity() {
	protected String toXMLHelper() { return ""; }
	public String getDisplayName() { return "None of the Above"; }
	public String getAuthorityName() { return "__NONE"; }
	public String getSortableString() { return "zzzzzzzzzzznone"; }
    };
    // Fields    

     private int id;
     private Date timestamp = new Date();
     private EntityOccurrence occurrence;
     private T selection;

     // Constructors

    /** default constructor */
    public Vote() {
    }

    /** full constructor */
    public Vote(EntityOccurrence occurrence, T selection) {
       this.occurrence = occurrence;
       this.selection = selection;
    }
   
    // Property accessors
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public EntityOccurrence getOccurrence() {
        return this.occurrence;
    }
    
    public void setOccurrence(EntityOccurrence occurrence) {
        this.occurrence = occurrence;
    }
    public T getSelection() {
        return this.selection;
    }
    
    public void setSelection(T selection) {
        this.selection = selection;
    }

}


