;
drop table if exists hib_artifact_keywords;
drop table if exists hib_artifacts;
drop table if exists hib_atomic_artifacts;
drop table if exists hib_building_artifacts;
drop table if exists hib_chunks;
drop table if exists hib_citations;
drop table if exists hib_coin_artifacts;
drop table if exists hib_date_ranges;
drop table if exists hib_dates;
drop table if exists hib_entities;
drop table if exists hib_entity_occurrence_params;
drop table if exists hib_entity_occurrences;
drop table if exists hib_frequencies;
drop table if exists hib_gem_artifacts;
drop table if exists hib_image_names;
drop table if exists hib_images;
drop table if exists hib_lang_abbrevs;
drop table if exists hib_languages;
drop table if exists hib_lemmas;
drop table if exists hib_parses;
drop table if exists hib_person_names;
drop table if exists hib_places;
drop table if exists hib_sculpture_artifacts;
drop table if exists hib_site_artifacts;
drop table if exists hib_toc_chunks;
drop table if exists hib_tocs;
drop table if exists hib_vase_artifacts;
drop table if exists hib_votes;
drop table if exists hib_word_counts;
create table hib_artifact_keywords (id integer not null auto_increment, artifact_id integer, artifact_type varchar(255), keyclass varchar(255), keyword varchar(255), primary key (id)) type=MyISAM;
create table hib_artifacts (artifact_id integer not null, name varchar(255), type varchar(255), location varchar(255), summary text, perseus_version varchar(255), entered_by text, sources_used text, other_bibliography text, documentary_references text, primary key (artifact_id)) type=MyISAM;
create table hib_atomic_artifacts (atomic_artifact_id integer not null, accession_number varchar(255), dimensions text, region varchar(255), start_date varchar(255), start_mod varchar(255), end_date varchar(255), end_mod varchar(255), unitary_date varchar(255), unitary_mod varchar(255), date_for_sort varchar(255), period varchar(255), period_for_sort varchar(255), culture text, context varchar(100), context_mod varchar(255), findspot text, findspot_mod varchar(255), collection varchar(255), date_description text, collection_history text, donor varchar(255), condit text, condition_description text, comparanda text, material varchar(255), material_description text, other_notes text, primary key (atomic_artifact_id)) type=MyISAM;
create table hib_building_artifacts (building_id integer not null, architectural_order text, architect varchar(255), architect_evidence text, building_type varchar(255), history text, plan text, see_also text, primary key (building_id)) type=MyISAM;
create table hib_chunks (id integer not null auto_increment, document_id varchar(50), element varchar(20), type varchar(30), value varchar(250), position integer, abs_position integer, chunk_id varchar(255), open_tags text, close_tags text, start_offset integer, end_offset integer, display_query varchar(100), head text, head_lang varchar(10), custom_head bit, lemma_id integer, primary key (id)) type=MyISAM;
create table hib_citations (id integer not null auto_increment, source_document_id varchar(45), source_subquery varchar(255), destination_doc_id varchar(50), destination_subquery varchar(255), resolved_destination_document_id varchar(60), resolved_destination_subquery varchar(255), link_type_code integer, source_header text, primary key (id)) type=MyISAM;
create table hib_coin_artifacts (coin_id integer not null, actual_weight varchar(255), commentary text, denomination varchar(50), die_axis varchar(255), issuing_authority varchar(255), obverse_legend text, obverse_type text, reverse_legend text, reverse_type text, primary key (coin_id)) type=MyISAM;
create table hib_date_ranges (date_range_id integer not null, date_range_start_date_id integer, date_range_end_date_id integer, primary key (date_range_id)) type=MyISAM;
create table hib_dates (date_id integer not null, date_year integer, date_month integer, date_day integer, date_hour integer, date_minute integer, date_second integer, date_sec_fraction double precision, primary key (date_id)) type=MyISAM;
create table hib_entities (id integer not null auto_increment, entity_type varchar(255) not null, auth_name varchar(75), display_name varchar(150), sort_string varchar(150), max_occ bigint, min_occ bigint, doc_count integer, idf double precision, primary key (id)) type=MyISAM;
create table hib_entity_occurrence_params (param_id integer not null, param_value varchar(255) not null, param_name varchar(255) not null, primary key (param_id, param_name)) type=MyISAM;
create table hib_entity_occurrences (id integer not null auto_increment, entity_id integer not null, document_id varchar(50), subquery varchar(200), position integer, display_text text, primary key (id)) type=MyISAM;
create table hib_frequencies (id integer not null auto_increment, type char(1) not null, max_freq integer, min_freq integer, weighted_freq double precision, keyword_score double precision, first_pos integer, tf double precision, tf_idf double precision, chunk_id integer, snippet text, entity_id integer, document_id varchar(255), primary key (id)) type=MyISAM;
create table hib_gem_artifacts (gem_id integer not null, category varchar(255), object_function varchar(255), graffiti text, inscription text, inscription_bibliography text, original varchar(255), original_or_copy varchar(255), placement varchar(255), primary_citation text, scale varchar(255), scale_for_sort varchar(255), sculptor varchar(255), sculptor_mod varchar(255), style varchar(255), form_style_description text, subject_description text, technique varchar(255), technique_description text, title varchar(255), sculpture_type varchar(255), in_group varchar(255), in_whole varchar(255), primary key (gem_id)) type=MyISAM;
create table hib_image_names (id integer not null auto_increment, archive_number varchar(255), name varchar(255), secondary_name varchar(255), tertiary_name varchar(255), image_schema varchar(255), primary key (id)) type=MyISAM;
create table hib_images (id integer not null auto_increment, type varchar(255) not null, archive_number varchar(255), caption text, credits text, date varchar(255), series varchar(255), seq varchar(255), entered_by varchar(255), lon varchar(255), lat varchar(255), status integer, canonical varchar(255), source_id varchar(255), format varchar(255), qt_name varchar(255), qt_movieName varchar(255), qt_controller varchar(255), qt_autoplay varchar(255), vr_bcolor varchar(255), playback_width varchar(255), playback_height varchar(255), primary key (id)) type=MyISAM;
create table hib_lang_abbrevs (language_id integer not null, abbreviation varchar(10) not null, idx integer not null, primary key (language_id, idx)) type=MyISAM;
create table hib_languages (id integer not null, display_name varchar(30) not null, has_morph_data bit, adapter_class_name varchar(255), primary key (id), unique (display_name)) type=MyISAM;
create table hib_lemmas (lemma_id integer not null, lemma_text varchar(100), bare_headword varchar(100), lemma_sequence_number integer, lemma_lang_id integer, lemma_short_def varchar(255), primary key (lemma_id)) type=MyISAM;
create table hib_parses (id integer not null auto_increment, lemma_id integer not null, morph_code varchar(13), expanded_form varchar(75), form varchar(75) not null, bare_form varchar(75), dialects varchar(50), misc_features varchar(50), primary key (id)) type=MyISAM;
create table hib_person_names (person_id integer not null, nameType varchar(15), name varchar(50), initial varchar(1), position integer not null, primary key (person_id, position)) type=MyISAM;
create table hib_places (place_id integer not null, place_longitude double precision, place_latitude double precision, place_site_name varchar(80), place_state varchar(60), place_nation varchar(60), primary key (place_id)) type=MyISAM;
create table hib_sculpture_artifacts (sculpture_id integer not null, assoc_building varchar(255), category varchar(255), object_function varchar(255), graffiti text, inscription text, inscription_bibliography text, original varchar(255), original_or_copy varchar(255), placement varchar(255), primary_citation text, scale varchar(255), scale_for_sort varchar(255), sculptor varchar(255), sculptor_mod varchar(255), style varchar(255), form_style_description text, subject_description text, technique varchar(255), technique_description text, title varchar(255), sculpture_type varchar(255), in_group varchar(255), in_whole varchar(255), primary key (sculpture_id)) type=MyISAM;
create table hib_site_artifacts (site_id integer not null, extent varchar(255), human_name varchar(255), region varchar(255), site_type varchar(255), description text, exploration text, periods varchar(255), physical text, primary key (site_id)) type=MyISAM;
create table hib_toc_chunks (toc_id integer not null, chunk_id integer, subquery varchar(255)) type=MyISAM;
create table hib_tocs (id integer not null auto_increment, class char(1) not null, document_id varchar(50), subquery varchar(200), scheme varchar(75) not null, working_scheme varchar(75), primary key (id), unique (document_id, subquery, scheme)) type=MyISAM;
create table hib_vase_artifacts (vase_id integer not null, ceramic_phase varchar(255), decoration_description text, essay_number varchar(255), essay_text text, graffiti varchar(255), inscriptions text, painter varchar(255), painter_mod varchar(255), attributed_by varchar(255), potter varchar(255), potter_mod varchar(255), primary_citation text, beazley_number varchar(255), relief varchar(255), shape varchar(255), shape_description text, ware varchar(255), primary key (vase_id)) type=MyISAM;
create table hib_votes (id integer not null auto_increment, type char(1) not null, time datetime, occurrence_id integer not null, entity_id integer, primary key (id)) type=MyISAM;
create table hib_word_counts (id integer not null auto_increment, document_id varchar(80) not null, language_id integer, word_count bigint, primary key (id)) type=MyISAM;
alter table hib_artifact_keywords add index FK88673639D3592270 (artifact_id), add constraint FK88673639D3592270 foreign key (artifact_id) references hib_entities (id);
create index name_idx on hib_artifacts (name);
create index artifact_type_idx on hib_artifacts (type);
alter table hib_artifacts add index FKD56395A3D3592270 (artifact_id), add constraint FKD56395A3D3592270 foreign key (artifact_id) references hib_entities (id);
create index collection_idx on hib_atomic_artifacts (collection);
create index period_idx on hib_atomic_artifacts (period);
create index context_idx on hib_atomic_artifacts (context);
create index material_idx on hib_atomic_artifacts (material);
create index region_idx on hib_atomic_artifacts (region);
alter table hib_atomic_artifacts add index FKD5362CCB3A697D27 (atomic_artifact_id), add constraint FKD5362CCB3A697D27 foreign key (atomic_artifact_id) references hib_entities (id);
create index architect_idx on hib_building_artifacts (architect);
create index building_type_idx on hib_building_artifacts (building_type);
alter table hib_building_artifacts add index FK6797CA9459167F22 (building_id), add constraint FK6797CA9459167F22 foreign key (building_id) references hib_entities (id);
create index doc_type_value_idx on hib_chunks (document_id, type, value);
create index doc_cid_idx on hib_chunks (document_id, chunk_id);
create index doc_so_eo_idx on hib_chunks (document_id, start_offset, end_offset);
create index doc_dq_idx on hib_chunks (document_id, display_query);
create index doc_so_eo_type_idx on hib_chunks (document_id, type, start_offset, end_offset);
create index doc_type_idx on hib_chunks (document_id, type);
create index doc_idx on hib_chunks (document_id);
create index doc_so_eo_type_val_idx on hib_chunks (document_id, type, value, start_offset, end_offset);
alter table hib_chunks add index FK226AD2249970ED3 (lemma_id), add constraint FK226AD2249970ED3 foreign key (lemma_id) references hib_entities (id);
create index source_idx on hib_citations (source_document_id, source_subquery);
create index resolved_destination_idx on hib_citations (resolved_destination_document_id, resolved_destination_subquery);
create index denomination_idx on hib_coin_artifacts (denomination);
create index issuing_authority_idx on hib_coin_artifacts (issuing_authority);
alter table hib_coin_artifacts add index FK51A965316E165402 (coin_id), add constraint FK51A965316E165402 foreign key (coin_id) references hib_entities (id);
alter table hib_date_ranges add index FK9BB554C960D587BD (date_range_end_date_id), add constraint FK9BB554C960D587BD foreign key (date_range_end_date_id) references hib_entities (id);
alter table hib_date_ranges add index FK9BB554C9C1359504 (date_range_start_date_id), add constraint FK9BB554C9C1359504 foreign key (date_range_start_date_id) references hib_entities (id);
alter table hib_date_ranges add index FK9BB554C94323C0C3 (date_range_id), add constraint FK9BB554C94323C0C3 foreign key (date_range_id) references hib_entities (id);
create index second_idx on hib_dates (date_second);
create index hour_idx on hib_dates (date_hour);
create index y_m_idx on hib_dates (date_year, date_month);
create index m_d_idx on hib_dates (date_month, date_day);
create index month_idx on hib_dates (date_month);
create index y_m_d_idx on hib_dates (date_year, date_month, date_day);
create index second_frac_idx on hib_dates (date_sec_fraction);
create index year_idx on hib_dates (date_year);
create index minute_idx on hib_dates (date_minute);
create index day_idx on hib_dates (date_day);
alter table hib_dates add index FKBF169847D33574 (date_id), add constraint FKBF169847D33574 foreign key (date_id) references hib_entities (id);
create index sort_string_idx on hib_entities (sort_string);
create index auth_name_idx on hib_entities (auth_name);
create index display_name_idx on hib_entities (display_name);
alter table hib_entity_occurrence_params add index FKE5798D5634B6FF9B (param_id), add constraint FKE5798D5634B6FF9B foreign key (param_id) references hib_entity_occurrences (id);
create index entity_doc_idx on hib_entity_occurrences (entity_id, document_id);
create index entity_doc_pos_idx on hib_entity_occurrences (entity_id, document_id, position);
create index doc_idx on hib_entity_occurrences (document_id);
alter table hib_entity_occurrences add index FK34FDAFE4FDFE16D4 (entity_id), add constraint FK34FDAFE4FDFE16D4 foreign key (entity_id) references hib_entities (id);
create index docID_entID on hib_frequencies (document_id, entity_id);
create index docID on hib_frequencies (document_id);
create index entID_chunkID on hib_frequencies (chunk_id, entity_id);
alter table hib_frequencies add index FKA337273CFDFE16D4 (entity_id), add constraint FKA337273CFDFE16D4 foreign key (entity_id) references hib_entities (id);
alter table hib_frequencies add index FKA337273C11DB9775 (chunk_id), add constraint FKA337273C11DB9775 foreign key (chunk_id) references hib_chunks (id);
create index sculpture_type_idx on hib_gem_artifacts (sculpture_type);
alter table hib_gem_artifacts add index FKAF1057B345F58096 (gem_id), add constraint FKAF1057B345F58096 foreign key (gem_id) references hib_entities (id);
create index archive_number_idx on hib_image_names (archive_number);
create index archive_number_idx on hib_images (archive_number);
alter table hib_lang_abbrevs add index FK51976BE787D1C0F (language_id), add constraint FK51976BE787D1C0F foreign key (language_id) references hib_languages (id);
create index bare_idx on hib_lemmas (bare_headword);
create index lemma_idx on hib_lemmas (lemma_text, lemma_sequence_number, lemma_lang_id);
alter table hib_lemmas add index FK3198814986F88722 (lemma_lang_id), add constraint FK3198814986F88722 foreign key (lemma_lang_id) references hib_languages (id);
alter table hib_lemmas add index FK319881499970ED3 (lemma_id), add constraint FK319881499970ED3 foreign key (lemma_id) references hib_entities (id);
create index lemma_id on hib_parses (lemma_id, morph_code, expanded_form, form);
create index bare_form_idx on hib_parses (bare_form);
create index form_idx on hib_parses (form);
create index form_lemma on hib_parses (lemma_id, form);
alter table hib_parses add index FK3835E29E9970ED3 (lemma_id), add constraint FK3835E29E9970ED3 foreign key (lemma_id) references hib_entities (id);
create index name on hib_person_names (name);
create index nameType_initial on hib_person_names (nameType, initial);
create index nameType_name on hib_person_names (nameType, name);
alter table hib_person_names add index FK651491DC6F428994 (person_id), add constraint FK651491DC6F428994 foreign key (person_id) references hib_entities (id);
create index nation_idx on hib_places (place_nation);
create index site_idx on hib_places (place_site_name);
create index lat_idx on hib_places (place_latitude);
create index state_idx on hib_places (place_state);
create index loc_idx on hib_places (place_longitude, place_latitude);
create index long_idx on hib_places (place_longitude);
alter table hib_places add index FK38C8EECA1E2E4520 (place_id), add constraint FK38C8EECA1E2E4520 foreign key (place_id) references hib_entities (id);
create index sculptor_idx on hib_sculpture_artifacts (sculptor);
create index category_idx on hib_sculpture_artifacts (category);
create index assoc_building_idx on hib_sculpture_artifacts (assoc_building);
create index object_function_idx on hib_sculpture_artifacts (object_function);
create index scale_idx on hib_sculpture_artifacts (scale);
alter table hib_sculpture_artifacts add index FK26326DC1E30DF056 (sculpture_id), add constraint FK26326DC1E30DF056 foreign key (sculpture_id) references hib_entities (id);
alter table hib_site_artifacts add index FKF10BAA67F951FA42 (site_id), add constraint FKF10BAA67F951FA42 foreign key (site_id) references hib_entities (id);
alter table hib_toc_chunks add index FK400F1DFB11DB9775 (chunk_id), add constraint FK400F1DFB11DB9775 foreign key (chunk_id) references hib_chunks (id);
alter table hib_toc_chunks add index FK400F1DFBAEDA94BF (toc_id), add constraint FK400F1DFBAEDA94BF foreign key (toc_id) references hib_tocs (id);
create index query_scheme_idx on hib_tocs (document_id, subquery, scheme);
create index query_idx on hib_tocs (document_id, subquery);
create index doc_scheme_idx on hib_tocs (document_id, scheme);
create index doc_idx on hib_tocs (document_id);
create index potter_idx on hib_vase_artifacts (potter);
create index painter_idx on hib_vase_artifacts (painter);
create index shape_idx on hib_vase_artifacts (shape);
create index ware_idx on hib_vase_artifacts (ware);
alter table hib_vase_artifacts add index FK1ADB2DDD5F5B882 (vase_id), add constraint FK1ADB2DDD5F5B882 foreign key (vase_id) references hib_entities (id);
alter table hib_votes add index FKC01A9C8BFDFE16D4 (entity_id), add constraint FKC01A9C8BFDFE16D4 foreign key (entity_id) references hib_entities (id);
alter table hib_votes add index FKC01A9C8B765577D7 (occurrence_id), add constraint FKC01A9C8B765577D7 foreign key (occurrence_id) references hib_entity_occurrences (id);
create index doc_id_lang_idx on hib_word_counts (document_id, language_id);
create index doc_id_idx on hib_word_counts (document_id);
alter table hib_word_counts add index FK5B78A05B787D1C0F (language_id), add constraint FK5B78A05B787D1C0F foreign key (language_id) references hib_languages (id);
create index type_idx on hib_entities (entity_type);
