package org.apache.jsp.about.publications;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MW2000_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/includes/index/header.jsp");
    _jspx_dependants.add("/includes/index/../head_search.html");
    _jspx_dependants.add("/includes/common/analytics.htm");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\n<head><title>Web Delivery of High-Resolution Images from the Museum of Fine Arts, Boston</title>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"/css/hopper.css\"/>\n<script type=\"text/javascript\" src=\"/js/hopper.js\"></script>\n</head>\n<body onload=\"checkRedirect();\">\n");
      out.write("<div id=\"header\">\n\t<a id=\"banner\" href=\"/hopper/\">\n\t</a>\n\t<div id=\"header_side\">\n\t\t");
      out.write("<form action=\"/hopper/searchresults\" class=\"search_form\" onsubmit=\"return validate_form(this,q);\">\n    <input name=\"q\" />\n    <input type=\"submit\" value=\"Search\" />\n    <p>(\"Agamemnon\", \"Hom. Od. 9.1\", \"denarius\")</p>\n    <p><a href=\"/hopper/search\">All Search Options</a> [<a href=\"javascript:abbrev_help()\">view abbreviations</a>]</p>\n</form>\n");
      out.write("\n\t</div>\n</div>\n");
      out.write("\n\n<div id=\"main\">\n    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/includes/index/indexNav.jsp" + (("/includes/index/indexNav.jsp").indexOf('?')>0? '&': '?') + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("tabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("about", request.getCharacterEncoding()) + "&" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("subtabActive", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("publications", request.getCharacterEncoding()), out, false);
      out.write(" \t\n    <div id=\"content\" class=\"2column\">\n        <div id=\"index_main_col\">\n\t\t<div id=\"publications\">\n<center>\n<p>\nPaper written for the session, \"Making Data Work: Functional Design Strategies\"<br> at <a href=\"http://www.archimuse.com/mw2000/\">Museums and the Web 2000</a></p>\n<p>April 17-19, 2000, Minneapolis, Minnesota<br>(Organized by Archives & Museum Informatics.)</p>\n\n<p>\nMaria Daniels, Perseus Project, Tufts University<br>\nSend me your <a href=\"mailto:maria@perseus.tufts.edu\">\ncomments</a> on this paper!<br>\n©2000 Archives & Museum Informatics. All Rights Reserved.</p></center>\n<hr size=\"4\" width=\"95%\" align=\"center\">\n<center><h3>Is Bigger Better? Web Delivery of High-Resolution Images \n\tfrom the Museum of Fine Arts, Boston</h3>\n<p><b>Abstract</b></p></center>\n\n<blockquote> \n<p>At the turn \n\t  of the twenty-first century, the first stage of museum digitization \n\t  is now well underway. Many museums have initiated and made headway on \n\t  projects to put their holdings on-line, package their collections management \n");
      out.write("\t  databases into Web sites, and produce curatorial content for a worldwide, \n\t  on-line audience. As institutions move into the second phase of these \n\t  developments, which emerging technologies show the most promise for \n\t  museums and their audiences? Which principles should form the core of \n\t  a museum's digitization strategy over the long term? How will improved \n\t  access to museum collections affect research possibilities for a broad \n\t  range of people, both in academia and among the general public?</p>\n\t<p>Working together since 1997 \n\t  to digitize an important collection of Roman art, the Perseus Project \n\t  and the Museum of Fine Arts, Boston, have addressed these and other \n\t  questions. This paper will focus on the development of a new archive \n\t  of photographs, and discuss the decision-making and technical processes \n\t  behind delivering high-resolution images of museum objects via the Web. \n\t  Copyright protection, storage and delivery of many large files, interface, \n\t  the viewer's experience, curatorial concerns, and other issues have \n");
      out.write("\t  been important considerations. Underlying our efforts has been the belief \n\t  that, in the new environment of networked access to museum resources, \n\t  museums have an opportunity to transform education.</p>\n      </blockquote>\n      <p>&nbsp;</p>\n      <p>Perhaps one of the most frustrating things about \n\tworking on the content side of a digital library is knowing how many resources \n\tin the library are not yet published and available to the world. Like \n\ta museum curator with limited gallery space and a storeroom full of artworks, \n\ta digital librarian is always thinking of the day, some time in the future, \n\twhen the unknown parts of the library will have their turn in the limelight. \n\tThis is why we are particularly happy to be able to present the work on \n\thigh-resolution images of Roman coins which the Perseus Project (<a href=\"http://www.perseus.tufts.edu\">http://www.perseus.tufts.edu</a>) \n\thas carried out in collaboration with the Museum of Fine Arts, Boston \n\t(<a href=\"http://www.mfa.org\">http://www.mfa.org</a>), with its curatorial \n");
      out.write("\tstaff in Art of the Ancient World, John Herrmann, Mary Comstock, and Pam \n\tRussell, and the museum's Director of Information Resources, Nancy Allen. \n\tThis collaborative effort with the MFA forms part of the continuing research \n\tand development at the Perseus Project, an effort now in its thirteenth \n\tyear, at Tufts University. Our work represents another major step toward \n\tthe electronic delivery of scholarly-level museum resources in a permanent, \n\tstandardized, flexible way.</p>\n\n      <p>The limitations of electronic resources, especially \n\tfor scholarly use, are well known to all of us; I outlined some of them \n\tin another Museums and the Web conference paper (Daniels, 1997). At that \n\tLos Angeles session, Prof. Charles Rhyne of Reed College made explicit \n\tthe particular problems of teaching art history using inadequate visual \n\tmaterials, and stressed, as he has in many of his publications, the necessity \n\tfor scrutinizing technical details, such as brush marks, or small parts \n\tof an object, like the dozens of tiny figures on a 12-foot-long Japanese \n");
      out.write("\tscreen (Rhyne, 1997). We agreed that scholars, students, and teachers \n\twould not truly be able to take advantage of the electronic environment \n\tfor their work until more, higher-resolution images were made available. \n\tAt Perseus, we had always concentrated on the <i>quantity</i> of images \n\twe included, up to 109 detailed views of a <a href=\"/hopper/artifact?name=Harvard+1960.367&object=Vase\">single \n\tGreek vase</a> . However, in the back of my mind was the annoying knowledge \n\tthat the Perseus Project did, in fact, have an archive of scanned and \n\tdigital camera photographs at a much higher resolution than the minimal, \n\t640x480 pictures we freely published on our web site. What was impeding \n\tthe distribution of images of a significantly higher quality? Could these \n\thigh-resolution pictures be the analytical tools our users still lacked?</p>\n<p>Later that year, as we embarked on the Perseus-MFA \n\tcollaboration that continues today, the question of delivering higher-resolution \n\tpictures was foremost. Work over the past two years has culminated in \n");
      out.write("\tthe electronic publication of a major catalogue of Roman art, including \n\t780 Roman coins and medallions, with a series of Perseus enhancements \n\tincluding a tool enabling viewers to zoom in on 18-megabyte photographs, \n\texamining the coins at up to 25 times their actual size. This paper will \n\tbegin by discussing the principles which guided us, then continue with \n\ta short description of our working methods. Finally, it will venture to \n\tsuggest some of the earliest results of this work. The question of the \n\ttitle, &quot;Is Bigger Better?&quot; is really a question for you, the \n\taudience of museum professionals, art educators, and everyone interested \n\tin electronic access to cultural resources. How can these big images be \n\tintegrated into an electronic museum experience, and what potential do \n\tthey hold for the transformation of museum collections into complete educational \n\tresources?</p>\n<p>As Skidmore &amp; Dowie (1999) point out, educators \n\timplementing technology do best to begin by articulating the educational \n");
      out.write("\tobjectives which need to be served. At the outset of our work, members \n\tof the team, including curators, museum educators, technical staff, and \n\tuniversity faculty, worked together to clarify the educational goals of \n\tthis project, and, further, to express a set of principles which would \n\tapply not only to the instructional uses of the data, but also to its \n\tlongevity and utility over time. It was particularly important that the \n\tcollaborators started with a discussion of the project's objectives; otherwise, \n\tdifferences between the museum and the university perspectives might have \n\tled to difficulties, had we failed to articulate our individual interests \n\tand work together to integrate them into a single approach at the outset.</p>\n\n<p>The first, and most important, principle guiding \n\tour work with the MFA coins was the understanding that these objects are \n\ttransformative. A coin portrait of a Roman emperor like Trajan, a depiction \n\tof the Mausoleum of Hadrian, a personification of Gaul being speared by \n");
      out.write("\ta Roman warrior, issued during Caesar's conquest of Gaul -- all of these \n\trepresentations have the power to change the way people understand the \n\tancient world. Yet I am not making a special argument for Roman coins, \n\teven though coins are among the hardest to view in a gallery setting, \n\tthe most challenging for curators and educators to label and explain, \n\tand the easiest to overlook when they are surrounded by a building full \n\tof larger, more emphatic art works. At the outset of our collaboration, \n\twe agreed that the experience of seeing a Roman coin could be enlightening, \n\tand we therefore included coins in our plans to digitize the Roman collection. \n\tWe also included glass, pottery, mosaics, jewelry, portable altars, mirrors, \n\tstatues, tomb reliefs, clothes pins, pieces of buildings, and other objects. \n\tOur approach, in short, was that if an object is worth collecting, it \n\tis worth digitizing. This principle was tested by the usual limitations \n\tof time and money, of course, and we used a few broad themes, such as \n");
      out.write("\tdaily life and Roman gods, to help direct our selection of objects. However, \n\twe avoided a &quot;greatest hits&quot;, &quot;sculpture only&quot;, or \n\tother such limiting approach to the collection, as much as possible, opting \n\tinstead to represent as wide and as deep a sample as we could. The work \n\tpresented here on coins is being extended to all 1,100 of the art works \n\twe have documented thus far.</p>\n<p>A second principle was that of integration, not \n\tonly of the different sources of information within the museum, but also \n\tof the newly digitized material with existing resources at the MFA and \n\tin the Perseus digital library. Written documentation for the Roman coins \n\tcame from extensive curatorial records which had not yet been added to \n\tthe museum's collections management database, and the museum insisted \n\tthat this digitization project, and all others, should produce data useful \n\tfor their main database. On the Perseus side, we were hoping to find added \n\tvalue for the new objects by placing them in context with the other holdings \n");
      out.write("\tin the Perseus digital library, including photographs and descriptions \n\tof Roman sites, an atlas of the ancient world, and the texts of Cicero, \n\tCaesar, Josephus, and other authors. One other consideration was the integration \n\tof several existing publications of the art works, where possible, in \n\torder to avoid reduplication of efforts, and to bring new users to the \n\tscholarship already in publication. The only exception to this integrative \n\tapproach was the creation of new photographs, which were deemed necessary \n\tin order to provide consistent coverage of the collection. Many objects \n\thad never been photographed in color, or never had detail photographs \n\tmade; the coins themselves were all photographed with a centimeter scale, \n\tin order to convey their relative size.</p>\n<p>A third underlying principle was one which hardly \n\tneeds elaboration here: control of ownership. Everyone involved agreed \n\tthat protecting these new resources, by asserting copyright, watermarking \n\tdata, and attaching ownership and credit information to the photographs, \n");
      out.write("\twas important. From the start, our goal was to publish the catalog of \n\tcoins on the World Wide Web, and make it freely available to the general \n\tpublic. However, we chose to implement several safeguards, to ensure that \n\tthe pictures would not be separated from their descriptive data. In the \n\tusual Perseus collaborative arrangement, the MFA retained ownership of \n\tthe data we produced, in exchange for allowing it to be published freely \n\ton the Web. Thus, we had an obligation to protect the data, even as we \n\tsought for it a wide general audience.</p>\n<p>Several more principles guiding us in this work \n\trelated to the data collection process in a more technical way. First, \n\twe determined to adopt and conform to existing standards, for the data \n\titself and for its structuring, as much as possible. Controlled vocabularies, \n\tstandardized spellings, TEI-conformant SGML tagging, standard image file \n\tformats and processing, and compatible database structures at the MFA \n\tand at Perseus all played roles in making our data coherent, and in allowing \n");
      out.write("\tthis work to scale successfully. The curators invested their time and \n\texpertise in determining whether the quality of existing documentation \n\twas adequate, and, if not, creating new catalog information that would \n\tmeet their standard. Time spent building tables of credit lines for objects, \n\tcompiling alternate names for the same representation (e.g. Castor and \n\tPollux, <a href=\"/hopper/artifactSearch?q=dioscuri&artifact=yes&image=yes\">the \n\tDioscuri</a>, marking up bibliographic references, and employing standard \n\tvocabulary sources, like the <a href=\"http://shiva.pub.getty.edu/aat_browser/\">Getty \n\tArt &amp; Architecture Thesaurus</a>, contributed to the robustness of \n\tthe data, and ultimately saved some effort in the processes of data entry \n\tand production for the web.</p>\n\n<p>It is worth noting that in some cases, standard \n\tclassification systems have not yet developed to include the highly specialized \n\tdata sets relevant to our work; as J&ouml;rgensen (1999) indicates in \n\ther thorough survey of image retrieval systems, it is still a struggle \n");
      out.write("\tto understand how people search for images, let alone to build adequate \n\tgeneralized systems to aid those searches. An example is the <a href=\"http://shiva.pub.getty.edu/tgn_browser/\">Getty \n\tThesaurus of Geographic Names</a>, which does not yet include all of the \n\tgeographic data from the Mediterranean which would be useful in classifying \n\tthe assorted geographic attributes of the art objects, including their \n\tfindspots, depictions of places, inscriptions naming places, or the sources \n\tof the objects' raw materials. To address this problem, we have sought \n\thelp from classification schemes of other specialized sources, including \n\tfield-specific publications and other archives of ancient art, and in \n\tsome cases developed structures ourselves, based on the Perseus-specific \n\tcontent. </p>\n<p>A second, critically important technical principle \n\twas longevity of data. One of the paradoxes of digitizing two-millennium-old \n\tart works was the knowledge that they themselves were likely to be legible \n\tlong after our databases and our digital cameras crumbled into dust, if \n");
      out.write("\twe failed to make the data portable. While the Web is the immediate delivery \n\tmechanism for our work, all of the data is structured so that it can be \n\trepublished in emerging formats for years to come. The Perseus Project \n\thas a long experience in developing this type of portable data; for almost \n\ta decade, the project developed back-end data in powerful relational databases \n\tand structured SGML, but delivered the material on CD-ROMs in a low-cost, \n\twidely available HyperCard front end. With the advent of the Web, we were \n\table to take this same data and port it to a Web front end within a matter \n\tof weeks. We have also successfully built delivery software for the same \n\tdata for a platform-independent version of our CD-ROMs (Crane 2000).</p>\n<p>The last technical principle we kept fixed firmly \n\tin mind was a focus on automating the digitization process. So much of \n\tthe work necessarily had to be done by hand: the positioning and lighting \n\tof each object for photography; the review of catalog information, and \n");
      out.write("\twriting of new materials; the checking to ensure images were correctly \n\tattached to the corresponding objects. Yet in every possible instance, \n\twe looked for automated tools which might speed the process, from batch \n\timage-processing software to database error-checking scripts to automatic \n\ttape backup.</p>\n<p>Our final two requirements as we commenced this \n\twork were seemingly disparate principles that have proven over time at \n\tPerseus to be actually quite complementary: we sought to promote scholarship \n\tand also to distribute our work to the widest possible audience. In pursuit \n\tof the former goal, we adopted the highest academic standards in compiling \n\tdigitized resources; in pursuit of the latter, we recognized that the \n\tdistribution medium for our work already far outstrips the distribution \n\tnetwork for traditional scholarship, and labored to provide the interface, \n\torganization, and tools that would facilitate the material's usefulness \n\tto a broader range of users.</p>\n<dir> \n\t<blockquote> \n");
      out.write("\t  <p>The change in less than a decade from reliance \n\t    on publication solely through hundreds or perhaps thousands of physical \n\t    copies to a network reaching tens of millions of machines has no clear \n\t    historical precedent. For the first time in history, it is possible \n\t    to conceive of providing a vast number of people with an extensive \n\t    set of tools and documents, facilitating types of exploratory learning \n\t    once possible only at the greatest research centers. An audience for \n\t    these tools and documents does exist; on the Perseus Web site, we \n\t    already see concrete examples of the ever increasing audience that \n\t    electronic publication can reach. (Crane, 1998)</p>\n\t</blockquote>\n\n</dir>\n      <p>The range of testimonials we constantly receive \n\tfrom site visitors, preliminary analyses of Web logs, and the sheer quantity \n\tof page requests the site receives (currently hovering around 200,000 \n\tpage requests per 24-hour period), together indicate that a digital library \n\thas the demonstrable ability to simultaneously serve scholarship and reach \n");
      out.write("\tan emerging broad audience. We will be able to evaluate site usage, to \n\tlearn more about our audience for the high-resolution images; for instance, \n\tby comparing image use at Internet 1 and Internet 2 schools, we will be \n\table to investigate how having the infrastructure for large downloads \n\twill affect use of those resources.</p>\n      <p>To summarize, the principles informing our approach \n\tto this work included: a broad inclusion of objects; integration of resources; \n\tcontrol of ownership; adherence to standards; emphasis on data longevity \n\tand portability; automation of the digitization process; promotion of \n\tscholarship; and, finally, acknowledgement of a wide audience in the general \n\tpublic.</p>\n      <p>From the principles we developed a fairly streamlined \n\twork process that has taken advantage of many current standards in digital \n\tlibrary work. In addition to the standard classification systems and data \n\tformats outlined above, we chose a range of software and hardware with \n\ta preference for robust, open-source solutions. Written documentation \n");
      out.write("\twas produced in a FileMaker Pro database designed to be compatible with \n\tboth the Museum of Fine Arts' collections management database, in FileMaker \n\tPro, and with the Perseus art and archaeology databases, in 4<sup>th</sup> \n\tDimension. After completion, this data was transferred into PostGres, \n\tan open-source SQL database program running on a Linux server, which allows \n\tus to run certain indexing functions, automatically generate cross-links \n\twith the rest of the digital library, and publish the data on the Web. \n\tThanks to these automated functions, Perseus can immediately associate \n\tterms in the new coin documentation with existing terms in the digital \n\tlibrary, and lead curious readers to a wide array of additional information; \n\tfor instance, when a site like Ostia is depicted on a coin, the word &quot;Ostia&quot; \n\tin the coin's description automatically links to other Perseus resources \n\ton Ostia in the Lookup Tool, including an article on Ostia in the <i>Princeton \n\tEncyclopedia of Classical Sites</i>, links to other objects depicting \n");
      out.write("\tor coming from Ostia, a set of pictures which include &quot;Ostia&quot; \n\tin their captions, an atlas page that will plot Ostia on a map, and bibliographic \n\tsources on <a href=\"http://www.perseus.tufts.edu/cgi-bin/sor?lookup=ostia\">Ostia</a>.</p>\n\n      <p>On the imaging side, the only stumbling points in \n\ta very smooth process have been, first, the proprietary format of the \n\tdigital photographs as the camera initially stored them, and second, the \n\tacquisition of enough hard disk space and RAM to manipulate, store and \n\tdeliver these quantities of visual information. Digital photographs were \n\tmade using a Kodak DCS 460 camera, chosen for its relatively high resolution \n\timages, its compatibility with our existing system of Nikon lenses, and \n\tits efficient work flow, with sufficient storage on removable cards. Once \n\tthe images were captured and backed up, they were converted to standard \n\tTIFFs, a time-consuming process run under the Photoshop Acquire mode which \n\twould have been greatly assisted by automated conversion software; we \n");
      out.write("\twere unable to develop this tool in-house, and Kodak did not produce it, \n\tbut fortunately a third party vendor, DSL Consulting Inc., has written \n\tan<a href=\"http://www.kodak.com/cgi-bin/US/en/developers/solutions/search/webSolutionsSearch.cgi?SubmissionID=588&amp;amp;drgCurrentState=2\"> \n\tAutoAcquire script</a> that finally addresses this problem.</span></p>\n      <p><span class=\"normal\">Once the images were converted to their delivery \n\tformat, we employed an assortment of identification and marking measures. \n\tAlthough current watermarking programs are not impervious to attack, they \n\tare a perfect mechanism for linking museum identity with each image. As \n\tPeticolas &amp; Anderson (1999) explain the current technical outlook, \n\t&quot;although most [watermarking] schemes could survive basic manipulations \n\tthey would not cope with combinations of them or with random geometric \n\tdistortions.&quot; Still, visible and invisible watermarks are demonstrably \n\tuseful tools that can be employed first, to link ownership information \n");
      out.write("\tto image files, and second, to ensure that each image is difficult to \n\tseparate from this identifying metadata.</p>\n      <p>In order to deliver large files across the net in \n\ta reasonably short time, we chose to tile the coin files into <a href=\"/hopper/image?img=1997.03.0019\">scrollable windows</a>; \n\tthe largest tiles are c. 475K in size and compress down to about 36K as \n\tJPEGs, due to their limited color palettes. Like <a href=\"http://now.cs.berkeley.edu:80/Td/GridPix/\">GridPix</a>, \n\ta tool developed at Berkeley, and other tiling programs, the Perseus tiler \n\tallows users to interactively zoom in to parts of an image and scroll \n\taround it, while minimizing the waiting time for tiles to appear. We are \n\tconstantly reminded that many visitors to Perseus dial up over slow modems, \n\tlog in from geographically far-flung places, and compete for bandwidth \n\twith hundreds of others using the same service providers. To speed access, \n\twe generated all the different sizes and tiles in advance, not on the \n\tfly, and stored the thumbnail size, small (600x400), medium (1530x1018), \n");
      out.write("\tand large (3060x2036) versions of the images in parallel directories on \n\tour server. A database keeps track of what resolutions exist for each \n\timage. For implementation, we first used standard archiving software to \n\tretrieve the high-resolution, 18 megabyte digital photographs from a tape \n\tarchive, then employed open source image packages, including PNM and ImageMagick, \n\tto convert them into their assorted derivative images.</p>\n\n      <p>An important innovation of the Perseus tiling program \n\tis a random rotation feature, which delivers each tile slightly rotated \n\ta random amount either right or left, within a narrow range. While not \n\taffecting the look of the displayed image, the random rotation protects \n\tthe tiles from re-use, by making it very difficult to reconstruct them \n\tinto a single, high-resolution image file.</p>\n      <p>A late improvement to the scrollable image window \n\thas been a side-by-side \n\timage display tool, still in the final stages of development, which \n\tallows for simultaneous display of two images at the series of available \n");
      out.write("\tresolutions. We strongly agree with commentators like Skidmore and Dowie \n\t(1999) that side-by-side image presentation is a core pedagogical approach \n\tin art history that has been sadly ignored by new technologies up until \n\tnow. In a 1997 evaluation, one of Rhyne's students commented that a setup \n\tpresenting two images provided &quot;distinct advantages&quot; for her \n\tstudy, making &quot;manipulation and location easy&quot; and facilitating \n\t&quot;side-to-side comparisons impossible in the museum.&quot; Her summary \n\topinion: &quot;The scant hour of frantic sketching and note-taking in \n\ta crowded room has few advantages over these clear, beautiful, easily \n\tmaneuvered and compared images which students can investigate individually.&quot; \n\tOur intention is that the Perseus image display tool will serve as a vessel \n\tfor teachers to construct and save sets of images in Perseus, just as \n\tthey now save sets of slides for the left and right carousels of their \n\tslide lectures. This tool, like other Perseus resources, has been built \n");
      out.write("\tgenerically, so that it will be able to handle a variety of image inputs, \n\tfrom coin pictures to page images of texts to custom maps.</p>\n\n      <p>How will access to these big images affect research \n\tpossibilities for a broad audience? We feel much the same curiosity expressed \n\tby Schwartz (1999), but enough confidence in what we have built to be \n\table to say we have indeed &quot;provided tools for accessing more (or \n\tmore meaningful) information than was previously available.&quot; The \n\tmuseum staff are pleased to have created a new public platform for the \n\tscholarship on so many objects in their collection, which has until now \n\tfound only a specialized audience. Users' first responses to the image \n\tdisplay tool and the high-resolution images have ranged from delight to \n\tglee. Proper evaluation, both by internal groups of teachers, museum educators, \n\tand advisors, and external evaluators, will take place as part of a grant \n\tfrom the Digital Library Initiative, Phase Two, from the National Science \n");
      out.write("\tFoundation, the National Endowment for the Humanities, and other government \n\tagencies. With this support, the Perseus-MFA collaboration is also continuing, \n\tand the ongoing focus will be to build generic digital library tools for \n\tthe humanities which will be made accessible to the wide audience. This \n\tset of tools is applicable not only to works of ancient art, but to other \n\thumanities sources, such as a First Folio of Shakespeare, a Renaissance \n\tItalian dictionary, the physical remains of ancient Rome, and a series \n\tof Giza mastabas replete with hieroglyphic inscriptions. Visitors to the \n\tPerseus web site will have the ability to examine high-resolution images \n\tof any of these resources, using the same image tools developed for the \n\tRoman art of the Museum of Fine Arts.</p>\n      <p>We may not be able to judge right away whether, \n\tas Schwartz asks, &quot;the site provide[s] a window of introduction that \n\twill make the use of the museum more meaningful,&quot; even if it might \n\tseem clear that giving visitors an improved capacity for scrutinizing \n");
      out.write("\tart in a way that is difficult to do through the vitrines, under the spotlights, \n\tor among the crowds in the galleries, would necessarily bring more nuance \n\tand meaning to their understanding of the works they see. My favorite \n\tstory on this subject is the true one of the Perseus web site user who \n\tprinted out catalog entries from the exhaustive Caskey-Beazley publication \n\tof Greek vases in the MFA, came to Boston, and walked around the galleries \n\twith printouts in hand, gaining appreciably more information from looking \n\tat the objects in tandem with the thousand-word curators' essays than \n\the ever could have from the 300-word labels.</p>\n      <p>Yet even with insufficient evidence to judge whether \n\tthe physical museum's use becomes more meaningful, we can be certain that \n\tthe museum has been transformed into a place now accessible, for the first \n\ttime, to a new constituency. Virtual visitors, who might never travel \n\tto Boston, can now see the collection from the Ivory Coast, from Brazil, \n\tfrom Italy, from Singapore, from other parts of our own country, and from \n");
      out.write("\thundreds of remote places. These visitors embody the same attitude Dierking \n\t&amp; Falk (1998) have observed in actual museum visitors: they &quot;profess \n\thigh to moderate interest in the subjects presented&quot; they have sought \n\tthe subject on the Web -- but at the same time profess &quot;low to moderate knowledge&quot; they have come looking for information. The virtual museumgoers already \n\tdemonstrate that providing on-line documentation of the museum's resources, particularly high-resolution images, transforms the museum and its collection from a local \n\tstorehouse open 60 hours a week to an internationally available educational resource open 24 hours a day, allowing more people to have an in-depth experience with the \n\tart works than ever before, and democratizing the opportunity for a thoroughgoing educational involvement with the collection.</p>\n\n      <p>In closing, I would like to thank Charles Rhyne for his challenging questions three years ago at this conference. I titled\tmy paper with a question, not because I can \n");
      out.write("      provide a simple answer, but because I hope the collaborative work of the Perseus Project and the Boston Museum of Fine Arts will prompt your own questions, comments, and \n      ongoing\tdiscussion about how high-resolution images can change our way of learning with art, by enhancing the way we are able to see it.\n<p>\n<b>Bibliography</b>\n\n<p>Crane, G., Jacob, R., Taylor, H., Scaife, R., and Allen, N. (1998). A Digital Library for the Humanities [online]. Funded proposal submitted to the NEH-NSF Digital Libraries \nInitiative, Phase II. Available: <a href=\"http://www.perseus.tufts.edu/Props/DLI2/dli2.htm\">http://www.perseus.tufts.edu/Props/DLI2/dli2.html</a>. (February 15, 2000).</p>\n\n<p>Crane, G., ed. (2000). <i>Perseus 2.0: Interactive Sources and Studies on Ancient Greece. Platform-Independent Version.</i> New Haven: Yale University Press. 2000.</p>\n\n<p>Daniels, M. (1997). A Wish-List of Web Resources for Humanities Scholarship [online]. Paper delivered at <i>Museums and the Web 97</i>. Available: \n<a href=\"http://www.perseus.tufts.edu/%7Emaria/MW97.html\">http://www.perseus.tufts.edu/~maria/MW97.html</a>. (February 15, 2000).</p>\n");
      out.write("\t \n<p>Dierking, L. &amp; Falk, J. (1998). Understanding Free-Choice Learning: A Review of the Research and its Application to Museum Web Sites. In D. Bearman &amp; J. Trant (Eds.) <i>Museums and the Web 97-99: Special Edition Proceedings</i>. CD ROM. Archives &amp; Museum Informatics, 1999.\n</p>\n\n\t\n<p>J&ouml;rgensen, C. (1999). Access to Pictorial Material: A Review of Current Research and Future Prospects. <i>Computers and the Humanities 33</i>, No. 4, 293-318.</p>\n\t\n<p>Rhyne, C. (1997). Images as Evidence in Art History and Related Disciplines. In D. Bearman &amp; J. Trant (Eds.) <i>Museums and the Web 97: Selected Papers</i> (pp. 347-361). \nPittsburgh: Archives &amp; Museum Informatics, 1997.</p>\n\t  \n\n<p>Rhyne, C. (1997). Student Evaluation of the Usefulness of Computer Images in Art History and Related Disciplines. <i>Visual Resources: An International Journal of Documentation, \nXIII</i>, No. 1, 67-81.</p>\n\t\n<p>Petitcolas, F. A. P. &amp; Anderson, R. J. (1999). Evaluation of Copyright Marking Systems. <i>Proceedings of IEEE Multimedia Systems '99</i>, vol. 1, 574-579.</p>\n");
      out.write("\t\n<p>Schwartz, D. (1999). Museums and Libraries in the Age of the Internet: Lessons Learned from a Collaborative Website. In D. Bearman &amp; J. Trant (Eds.) <i>Museums and the \nWeb 97-99: Special Edition Proceedings</i>. CD ROM. Archives &amp; Museum Informatics, 1999.</p>\n\n\t\n  <p>Skidmore, C. &amp; Dowie, S. (1999). Camera Lucida: AMICO in an Art History Classroom. In D. Bearman &amp; J. Trant (Eds.) <i>Museums and the Web 97-99: Special Edition \n  Proceedings</i>. CD ROM. Archives &amp; Museum Informatics, 1999.</p>\n<p>\n\t\t</div> <!-- Publications div -->\t\n\t</div> <!-- main_col div -->\n        \n    </div> <!-- 2column div -->\n</div> <!-- main div -->\n\n<!-- Google Analytics --> \n");
      out.write("<script type=\"text/javascript\">\nvar gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\ndocument.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\n</script>\n<script type=\"text/javascript\">\nvar pageTracker = _gat._getTracker(\"UA-4545594-2\");\npageTracker._initData();\npageTracker._trackPageview();\n</script>");
      out.write("\n\n</body>\n</html>\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
